var lsz = 130;

var Col0 = Array([lsz]);

Col0[0] = "The present invention pertains to the technical fields of production and testing of condom and glove products. The invention specifically discloses a type of real-time monitoring, feedback, identification and consistent labeling system for quality information of condom and glove products. The system includes a collection module, a processing output module connected to the collection module, an application module connected to the processing output module, and also a query module. This system allows users (consumers) to obtain real-time collected product production data or pre-entered, encryption code or pre-entered information data from each product and to compare these data with pre-entered product performance indexes. The invention provides a solution to the problem of failure in individual product quality verification and its trace objectively and directly due to absence of independent information code that are applied in real time and that is in conformity to the corresponding product, thus preventing mixture of unqualified products with qualified products, intentionally or not, and partial or complete package recycling for resale to further endanger users\' interest and block the implementation of supervision. Therefore, responsibility and self-discipline on the part of the manufacturer will be improved and both supervisory officials and consumers are told to further distinguish the product quality.";

Col0[1] = "A mobile saw stand brake system incorporates a pair of swing-out legs pivotally connected to a saw stand main frame. A first end of the main frame is supported on a pair of rotating wheels. A \rpair of brake lever arms, each having a brake shoe end and a distal actuating end, are pivotally connected to the main frame. A tension mechanism is interconnected with the pair of swing-out legs so as to actuate the brake lever arms to engage the wheels when the legs are extended in their swing--out position. The brakes are disengaged when the swing-out legs are folded into a stowed position. ";

Col0[2] = "A digital sound processing design system for a vehicle audio system includes a computer and a design tool that is run by the computer. The design tool allows a user to define sound processing criteria that is stored in a template file. \rAn audio signal processor is connected to the first and second real channel inputs of an audio source. Memory that is coupled to the audio signal processor stores the template file. The sound processing engine that is coupled to the audio signal processor and the memory reads the template file at run-time to obtain the sound processing criteria. The sound processing engine applies the sound processing criteria to the first and second real channel inputs. The design tool allows a user to create virtual channel inputs and outputs that are based, in part, on the first and second real channel inputs. ";

Col0[3] = "A nanoflotation system used to separate suspended solids or large settling or floating solids from water, waste water or liquids. This is accomplished through the use of submerged membranes,ll,23, in combination with five design components; froth flotation, 4, gravity settling,9, pre coating of the submerged membranes,6, spacing, figure 4,of the membranes to facilitate flotation of solids to the surface or to the bottom of the containment chamber holding the submerged membranes, and membrane structures which use large diameter hollow fibre or tubular membranes and/or large pore opening membrane materials.";

Col0[4] = "A roller load support, for mounting on a load carrying vehicle such as a lift truck, has an elongate frame with a forwardly tapering vertical thickness and an upper surface for insertion beneath the underside of a load. Different longitudinally spaced pluralities of transverse upper rollers are movable upwardly to protrude through the frame\'s upper surface to engage the underside of the load during the insertion process. During the insertion process, the upper rollers are pushed upward by corresponding different pluralities of transverse lower rollers which rotatably engage the floor or other surface beneath the frame and frictionally counter-rotate the upper rollers. The lower rollers are spaced nonuniformly relative to each other along the length of the frame, with such spacings increasing progressively in size, within each plurality of lower rollers, in a forward direction toward the front end of the frame. Conversely, each such plurality of lower rollers has sequentially corresponding nonuniform spacings which decrease progressively in size, from plurality to plurality, in the forward direction.";

Col0[5] = "Systems and methods for wirelessly transmitting power between an industrial vehicle and an attachment, using an inductive power transfer unit (1 10) comprising an inductive power transmitter (1 18) and an inductive power receiver (120). Preferably, the inductive power transmitter (1 18) transmits wireless power to the inductive power receiver (120) over a range of motion of a vertically moveable carriage (114) of the industrial vehicle.";

Col0[6] = "A bulk material analyzer is variably constructed from an assembly of components. \rThe analyzer is the type that is used to analyze bulk material transported on a conveyor belt through an activation region between at least one radiation source and at least one radiation detector within the bulk material analyzer. The assembly includes a radiation-source box for disposition either above the activation region or below the conveyor belt; a radiation-detector box for disposition on the opposite side of the activation region and the conveyor belt from the radiation-source box; and a set of stackable structural beams predominantly containing radiation shielding material and configured for stacking about the activation region, the radiation-source box and the radiation-detector box to prevent unwanted radiation being generated and transported to the radiation-detector box. ";

Col0[7] = "Methods and systems relate to recovering hydrocarbons from within formations in which hydrocarbon bearing reservoirs are separated from one another by a fluid flow obstructing natural stratum. Relative to the reservoirs, the stratum inhibits or blocks vertical fluid flow within the formation. Drilled bores arranged to intersect the stratum provide an array of fluid flow paths through the stratum. Fluid communication established by the drilled bores enables production utilizing a producer borehole deviated from vertical and processes that rely on techniques such as gravity drainage through the fluid flow paths and/or injection through the fluid flow paths. ";

Col0[8] = "Methods and apparatus relate to both generating steam for injection into a wellbore and capturing carbon dioxide (CO2) produced when generating the steam. A direct steam generator (DSG) makes the steam by contacting water with a combustion area for hydrogen and oxygen. Quantity of the steam made exceeds quantity of water input into the steam generator since the steam includes vaporized water resulting from combustion of the hydrogen and oxygen mixed with the water inputted and heated. Steam-methane-reforming or autothermal- reforming produces the hydrogen stripped of the CO2 prior to introduction into the steam generator. Further, an air separation unit supplies the oxygen to the steam generator.";

Col0[9] = "Methods and systems relate to generating a flow of steam and splitting the flow of steam to enable both its injection into a formation to assist in oil recovery and its introduction into a pathway where the steam is used for generating electricity and capturing carbon dioxide (CO2). \rAt least part of the CO2 that is captured comes from burning of fuel used to generate the steam. \rSteam assisted gravity drainage requires the steam that is injected to have a higher pressure than the steam that is needed for CO2 capture. Exhaust steam from a steam turbine used to generate the electricity reduces pressure of the steam prior to use of the steam for capturing CO2. ";

Col0[10] = "Methods and systems relate to in situ combustion utilizing configurations of injection and production wells to facilitate the in situ combustion. The wells define vertically deviated lengths that have different orientations from one another. Further, heating processes such as resistive heating and cyclic steam stimulation may take place in one or both of the injection and production wells to precondition a reservoir prior to the in situ combustion.";

Col0[11] = "Methods and apparatus relate to producing hydrocarbons. Injecting a fluid mixture of steam and carbon dioxide into a hydrocarbon bearing formation facilitates recovery of the hydrocarbons. Further, limiting amounts of non-condensable gases in the mixture may promote dissolving of the carbon dioxide into the hydrocarbons upon contact of the mixture with the hydrocarbons.";

Col0[12] = "Methods and apparatus relate to processes and systems that introduce microwaves into mixtures containing hydrocarbons. The microwaves cause heating of the hydrocarbons in order to upgrade the hydrocarbons. Such upgrading occurs after recovering the hydrocarbons from within a formation and results in lowering viscosity of the hydrocarbons to enable transportation of the hydrocarbons to offsite locations, such as a refinery.";

Col0[13] = "Methods and apparatus relate to in situ combustion. Configurations of the injection and production wells facilitate the in situ combustion. Utilizing wet combustion for some embodiments promotes heat displacement for hydrocarbon recovery with procedures in which one or more of the production and injection wells are configured with lengths deviated from vertical. In some embodiments for either dry or wet combustion, at least the production wells define intake lengths deviated from vertical and that are disposed at staged levels within a formation. Each of the productions wells during the in situ combustion allow for recovery of hydrocarbons through gravity drainage. Vertical separation between the intake lengths of the production wells enables differentiated and efficient removal of combustion gasses and the hydrocarbons. ";

Col0[14] = "Methods and apparatus relate to systems and methods of recovering oil from a formation. \rIn operation, a steam chamber develops as a result of steam injection into the formation and the recovery of fluids including the oil through a production well. An auxiliary well spaced in a lateral direction from the production well helps ensure development of the steam chamber as desired. The auxiliary well may enable heating of the formation through establishing an electric potential between the auxiliary well and the production well or by resistive heating of material forming the auxiliary well. Further, the auxiliary well may provide a flow path for solvent or gas injection to facilitate the recovery through the production well. ";

Col0[15] = "Methods and systems relate to recovering petroleum products from an underground reservoir. Injection of steam along with carbon dioxide into the reservoir facilitates the recovering, which is further influenced by operating pressure for the injection. Absorption of the carbon dioxide by the products and heat transfer from the steam to the products act to reduce viscosity of the products in order to aid flowing of the products. ";

Col0[16] = "Methods and systems are provided for allocating production among reservoir compartments by way of compositional and isotopic analyses. That is, where individual reservoir compartments contribute differing amounts of fluid to a commingled production stream, the methods herein determine the relative contribution of fluid volume from each reservoir compartment. Both a composition-based relative contribution and an isotope-based relative contribution of fluid from each reservoir compartment may be determined to allocate production to each reservoir compartment, the determinations respectively being based on composition mass balances and stable carbon isotope mass balances of components. The combination of both allocation analyses provides quality checks on the results that identify improper allocations that may arise. In addition to production allocation, other applications include, among others, determining the effectiveness of intervention operations and providing feedback for adjusting operations. Advantages include lower costs, higher accuracies, and ease of use as compared to conventional methods.";

Col0[17] = "The invention relates to a double string pump for pumping liquids to the surface of a hydrocarbon well and especially a hydrocarbon well that is producing both natural gas and liquid fluids. The double string pump includes a hollow tube that raises and lowers the plunger and carries the liquids to the surface and an outer tube receives liquids down into the well to lubricate the moving parts and flush particles from areas prone to wear and back toward the production tube. The natural gas is produced through the annulus between wellbore casing and the outer production tubing string.";

Col0[18] = "The invention relates to an arrangement for positively pumping liquids to the surface of a hydrocarbon well where the hydrocarbon well has bee previously completed with a permanent packer and tailpipe. A rod pump having a plunger connected to a hollow rod string can positively pump the liquids collecting at the bottom of the well while the natural gas is produced up the annulus between the production tubing and the hollow rod string. In this invention, the tail pipe is perforated above the rod pump and below the packer to all the natural gas into the production tubing.";

Col0[19] = "The invention relates to a slim hole production system for pumping liquids to the surface of a hydrocarbon well and especially a hydrocarbon well that is producing both natural gas and liquids where the diameter of the hole in the production area is too small to get production tubing and a sucker rod into a productive arrangement. The slim hole pump includes a hollow tube that raises and lowers the plunger and carries the liquids to the surface and uses the annulus to produce the gas.";

Col0[20] = "Methods and systems are provided for acquiring seismic data in a marine environment using survey paths following a series of linked curved paths so as to obtain multi-azimuthal data over a sub-surface target. Marine vessels towing multiple seismic streamers may be configured to travel substantially along a series of linked deviated paths or a series of linked curved paths. Sources may be excited to introduce acoustic wave energy in the marine environment and into the subsea region. The acoustic wave energy then reflects and refracts from the subsea region to form reflected and refracted wave energy, which is detected by seismic receivers spaced along the streamers. The detected seismic data is then interpreted to reveal seismic information representative of the surveyed subsea region. Other enhancements include configuring the streamers in a flared configuration, where the lateral spacing increases rearwardly over the length of the seismic streamers.";

Col0[21] = "A method for accelerating start-up for steam assisted gravity drainage operations comprising the steps of: forming a steam-assisted gravity drainage production well pair comprising an injection well and a production well within a formation; beginning a pre-soaking stage by soaking one or both of the wellbores of the well pair with a solvent; beginning a pre-heating stage by heating the wellbores of the well pair; beginning a squeezing stage by injecting steam into the wellbores of the well pair; and beginning steam-assisted gravity drainage production.";

Col0[22] = "A process for increasing the efficiency of hydrocarbon recovery from an underground formation containing viscous hydrocarbons through the use of both gravity drainage and mobile water drive. The process comprises a pair of vertically-spaced horizontal wells and a laterally offset horizontal well. A heated fluid is injected into the formation via a first well pair, and an adjacent horizontal well creates a pressure sink to draw the heated fluid laterally to assist growth of the formation drainage area for hydrocarbon recovery improvement. Injected fluids recovered from both producers are collected for recycling.";

Col0[23] = "Autonomous Underwater Vehicles (AUV) collect and transmit information about ice floe thickness; this is combined with SYNTHETIC APERTURE RADAR images from satellites to identify and track dangerously thick regions of ice. The overlayed data is presented graphically to allow tracking of the thick ice regions over time. This information is used to alert drilling platforms in icy ocean conditions of pending ice floe dangers.";

Col0[24] = "The invention relates to a seismic acquisition process where the streamers are intentionally directed to follow an oscillating sweep pattern behind a tow vessel to counteract the effect of the large gaps between the streamers while acquire a wide sweep of data through each pass over the survey area.";

Col0[25] = "A belt weighing system comprising a weigh frame, an entry transition support structure and an exit transition support structure positioned on either sides of the weigh frame. The weigh frame preferably includes a plurality of closely spaced idlers to support a conveyor belt. The optional entry transition support structure can include one or more second belt support components, and the optional exit transition support structure can include one or more third belt support components. In one example form, a plurality of closely spaced idlers is also provided to support the belt adjacent or near the weigh frame in the transition regions. \rThe plurality of closely spaced idlers reduces, ameliorates or controls belt sag at or near the weigh frame and thus reduces errors that are otherwise introduced by relative material movement or other non-linear dynamic effects along the conveyor belt. ";

Col0[26] = "A treatment method includes the steps of: Providing an initial supply of an ammonium octamolybdate precursor powder having a bi-modal particle size distribution; applying a quantity of solvent to the initial supply of ammonium octamolybdate precursor powder to form a moistened intermediate powder; and allowing the moistened intermediate powder to adsorb the applied solvent over a time period, the quantity of solvent applied and the time period being sufficient to form a treated ammonium octamolybdate powder composition having a substantially uni-modal particle size distribution.";

Col0[27] = "A method of operating a directional drill rig from a remote location may involve the steps of: Issuing instructions from a remote location using a remote communications system; receiving said instructions at a drill site location using an on-site communications system; applying said instructions to a directional drill rig; and communicating directional drill rig data from the drill site location to the remote location using the remote and on-site communications systems.";

Col0[28] = "A waxless modular seal prevents leaks in the connection between the base of a toilet and the drain pipe. The waxless modular seal comprises a rubber portion and a resiliently compressible toroid-shaped foam ring, both of which are, in combination, designed to replace a traditional wax seal. The waxless modular seal captures the foam ring between an upper sealing ring and a lower sealing ring. Each sealing ring and the foam ring comprises a protrusion and at least one vertically disposed aperture, the apertures being sized sufficiently so as to allow a fastener to pass through the apertures. The foam ring may comprise a plurality of foam rings.";

Col0[29] = "A pay television satellite broadcast includes validation data that can be used to validate authenticity of live global positioning system (GPS) data. The validation data may be included within entitlement messages and encrypted for security and selective reception by authorized receivers. A navigation system may compute checksums of received live GPS data and compare with the validation data for a match. A decision about whether or not to use the live GPS data may be taken based on whether or not the computed checksums match the validation data received via the pay television satellite broadcast signals.";

Col0[30] = "A water vapor transport membrane comprises a nanofibrous layer disposed on a macroporous support layer, the nanofibrous layer coated with a water permeable polymer. A method for making a water vapor transport membrane comprises forming a nanofibrous layer on a macroporous support layer and applying a water permeable polymer to the nanofibrous layer. The water permeable polymer can be applied for so that the nanofibrous layer is substantially or partially filled with the water permeable polymer, or so that the coating forms a substantially continuous layer on one surface of the nanofibrous layer. In some embodiments of the method, the nanofibrous layer is formed by electro-spinning at least one polymer on at least one side of the porous support layer. In some embodiments, the support layer is formable and the method further comprises forming a three-dimensional structure from the water vapor transport membrane, for example, by compression molding, pleating or corrugating.";

Col0[31] = "A heat and humidity exchanger comprises panels made up of membrane sheets attached on either side of a separator. Channels extend across each panel between the separator and the membrane sheets. The panels are much stiffer than the membrane sheets. Panels are stacked in a spaced apart relationship to provide an ERV core. Spacing between adjacent panels may be smaller than a thickness of the panels,";

Col0[32] = "An elastomer lined self-locking tie (100, 600) is disclosed which includes an elongated strap (102, 602, 702), at least one cavity (104, 604, 704) disposed in the elongated strap (102, 602, 702), an elastomer segment (106, 606, 706), and a locking head (108, 608). The elongated strap (102, 602, 702) includes a head end (112, 612) positioned opposite a tapered end (114, 614, 714). The tapered end (114, 614, 714) includes a first surface (116, 616) positioned opposite a second surface (118, 618). The cavity (104, 604, 704) is positioned in either the first surface (116, 616) or the second surface (118, 618). The elastomer segment (106, 606, 706) is positioned within the cavity (104, 604, 704) and extends beyond either the first surface (116, 616) or the second surface (118, 618). The locking head (108, 608) extends from the head end (112, 612) of the elongated strap (102, 602, 702) and includes an orifice (124, 624) shaped to receive the tapered end (114, 614, 714) of the elongated strap (102, 602, 702) and the elastomer segment (106, 606, 706).";

Col0[33] = "This invention comprises systems, methods and apparatus for mud pulse telemetry involving sending benchmark pulses with known characteristics (such as amplitude or duration) from the surface to the BHA, measuring those characteristics at the BHA, using those measurements to predict the likely attenuation of downhole-to-surface mud pulse transmissions, and adjusting those transmissions to compensate for high attenuation or to obtain energy savings (or transmission rate increases) during low-attenuation conditions. Further refinements on these systems and methods, particularly concerning the use of signal-to-noise ratio measurements at the surface to more efficiently predict attenuation, are also disclosed.";

Col0[34] = "A mud hammer is driven by the flow of drilling fluid to generate pressure pulses. Timing and/or amplitude of the pulses are altered to encode data by applying electromagnetic forces to a movable member of the mud hammer. In an example embodiment the movable member carries one or more magnets and electromagnetic forces are applied to the movable member by one or more electromagnets. The mud hammer may also generate electrical power that may be applied to charge batteries and/or drive downhole electrical apparatus.";

Col0[35] = "A mud motor has integrated rotatable reamer elements. The reamer elements may be located directly radially outwardly of a rotor of the mud motor on an outer surface of the mud motor. The reamer elements may be applied to provide one or more of sizing a wellbore, smoothing a wellbore and stabilizing a bottom hole assembly and/or drill bit during drilling. The reamer elements may project from pockets formed in an outside surface of the mud motor. Axes of rotation of the reamer elements may be parallel to and/or skewed relative to a longitudinal centerline of the mud motor. Reamer devices that connect at couplings between drill string sections may be used together with the mud motor or applied separately of the mud motor. The reamer devices include inwardly-projecting elements that engage gaps between the drill string sections.";

Col0[36] = "A sprinkler fitting comprises a spout and a deflector moveably connected to one another, the deflector being formed from a resilient material in a single piece. The sprinkler fitting may be manufactured by; forming a spout; moulding a deflector in a resilient plastics material; and pressing the deflector onto the spout.";

Col0[37] = "A sprinkler base is provided comprising a platform component and a flow component. The flow component may have a tubular body encompassing a flow passage. A fluid inlet and a first fluid outlet may communicate with each other via the flow passage. The first fluid outlet may be arranged to receive a sprinkler head extending perpendicularly to an axis of the tubular body. The platform component may include mounting means to hold the tubular body of the flow component. Restraint means may be provided to retrain the tubular body against rotation about the axis of the tubular body relative to the platform component in one of a plurality of rotational positions.";

Col0[38] = "An aquarium cleaning device having an inner component (10) with a plate (16) employing a cleaning surface (30) and an alternative cleaning element (36) operative on a second surface opposite the cleaning surface. A magnetic element (28, 20) is carried by the plate and means for providing orienting buoyancy (24, 26, 28) is earned adjacent one end of the plate. An outer component (12) has a body (38) with a surface for engaging the exterior of an aquarium wall. A second magnetic element (40, 42) is carried by the body such that the body is positionable for magnetic attraction between the magnetic elements with the cleaning surface adjacent the aquarium wall or with the second surface adjacent the aquarium wall. By moving the body between the first and second positions, the inner component is flipped within the aquarium to alternate the cleaning elements. ";

Col0[39] = "A log singulator has first and second segments supported between roller mechanisms that allow the first and second segments to be reciprocated up and down. Each segment has a plurality of steps. Structural members of one segment extend between steps of the other segment. Some log singulators have first and second stages that can be independently operated. A first stage takes logs from a log pile and delivers the logs to a second stage that singulates the logs and delivers the logs to an output. A log storage area may be provided between the first and second stages. The first stage may operate at a higher cycle rate than the second stage. The second stage may be designed for rapid operation and good singulation of a range of log diameters. Embodiments of the first and second stages may be used in stand-alone applications and/or in combination with other log elevating and or singulating devices.";

Col0[40] = "\rThe present invention provides a skirted foundation that can be used in a jack-up rig for providing enhanced bearing capacity. The skirted foundation comprises a spudcan footing having an upper part and a base, wherein the upper part and the base are coupled at their peripherals to form an outer edge, wherein both the upper part and the base have a flat or conical configuration, and wherein the upper part supports one leg of a jack-up rig, and the base has a flat bottom or downward slope, and a skirt having an upper end being integrally coupled to the spudcan footing and downwardly projected to encircle the base and a lower end for penetrating seabed, wherein the skirt comprises a plurality of circumferential openings adjacent to the base of the spudcan footing and located within the top half of the skirt height.\r ";

Col0[41] = "Apparatus for securing products are provided. Each of a pair of elongate retaining members is pivotally secured at a first end of a base. Each of a pair of carriages is movable along a corresponding one of the retaining members and fixable to the corresponding one of the retaining members at a plurality of locations. Each carriage has a clip for capturing a projecting portion of the product. A stop member engages a portion of the product spaced apart from the projecting portions captured by the clips. The stop member is movable toward the clips in a single degree of freedom and is fixable to the base at a plurality of locations along the degree of freedom. Methods of securing a product using the apparatus are provided.";

Col0[42] = "This application relates to a track assembly for supporting wall studs. The assembly includes an upper track and a lower track each having a base and opposed first and second sidewalls. A plurality of tabs are formed in the track sidewalls at spaced longitudinal intervals. Each tab defines a slot between the tab and an adjacent portion of the sidewall for slidably receiving a wall panel of a stud. In one embodiment the tabs are punched-out portions of the sidewalls formed in a metal press and each comprise a fixed end proximal to the track base and a free end distal from the base. The track assembly allows wall studs to be quickly and removably coupled to the tracks without the need for ladders, fasteners or special tools. In one embodiment the assembly is a slip track system permitting deflection of the upper track relative to the lower track after installation of the wall studs.";

Col0[43] = "An outboard motor carrier comprises a frame, a motor support structure to which an outboard motor may be attached, and upper and lower wheels. The lower wheels are rotatably attached to a lower region of the frame so as to support the carrier when it is tilted from an upright standing position. The upper wheels are rotatably attached to an upper region of the frame so as to facilitate loading the carrier onto a bed of a vehicle and to support the carrier when in a reclined position. The motor support structure is attached to a mid region of the frame and may comprise a transverse mounting board. The lower region of the frame may operate as a stand when the carrier is an upright standing position. The carrier is configured to hold an attached outboard motor in a semi-upright position when it is in its reclined position.";

Col0[44] = "A method of generating a control signal is disclosed. The method includes the steps of: generating one or more control messages to be transmitted; and multiplexing the one or more control messages to generate a control message block to generate the control signal to be transmitted in a transport channel, wherein the control message block varies in length according to the number of control messages multiplexed and the size of the control messages; and wherein information on the number of control messages multiplexed and/or the size of the respective control messages is not included in the control signal. ";

Col0[45] = "A user device which has at least a connected mode (CONN) and an idle mode (IDLE) is provided with: a measurement unit which measures wireless quality in idle mode in accordance with information to be measured which indicates that the user device is preset so as to notify a base station of a wireless quality measurement value; a storage unit which stores the information to be measured and the wireless quality measurement value measured by the measurement unit; and a transmission unit which, when a predetermined notification condition (log exist condition, fig. 3) is satisfied, in connected mode, transmits an indicator which shows that a wireless quality measurement value exists to a base station, and transmits a notification signal which contains the wireless quality measurement value in response to a request from the base station.";

Col0[46] = "A method in which a user apparatus including at least operation modes of a connection mode (CONN) and an idle mode (IDLE), includes: a measurement unit that measures radio quality in the idle mode according to measurement target information indicating that the user apparatus is set beforehand to report a measurement value of radio quality to a base station; a storage unit that stores the measurement target information and the measurement value of radio quality measured by the measurement unit; and a transmission unit that transmits, in the connection mode, an indicator indicating that there is the measurement value of radio quality to the base station, and transmits a report signal including the measurement value of radio quality according to a request from the base station, wherein when a predetermined condition for deleting measurement target information (configuration flush condition) is satisfied, the storage unit deletes the measurement target information. ";

Col0[47] = "\rTo provide a radio base station apparatus and radio communication method capable of performing radio communications using downlink reference signal structures suitable for antenna virtualization, a radio base station apparatus (200) has a plurality of transmission antennas, generates CRSs used in demodulation of at least downlink control information, CQI-RSs generated for each of the transmission antennas used in measurement of channel quality, and DM-RSs generated for each stream used in demodulation of downlink transmission data, and multiplexes the CRSs, CQI-RSs and DM-RSs into a same transmission time unit to transmit from each of the antennas. \r ";

Col0[48] = "An ion manipulation method and device is disclosed. The device includes a pair of substantially parallel surfaces. An array of inner electrodes is contained within, and extends substantially along the length of, each parallel surface. The device includes a first outer array of electrodes and a second outer array of electrodes. Each outer array of electrodes is positioned on either side of the inner electrodes, and is contained within and extends substantially along the length of each parallel surface. A DC voltage is applied to the first and second outer array of electrodes. A RF voltage, with a superimposed electric field, is applied to the inner electrodes by applying the DC voltages to each electrode. Ions either move between the parallel surfaces within an ion confinement area or along paths in the direction of the electric field, or can be trapped in the ion confinement area.";

Col0[49] = "Thrust systems for passenger aircraft provide at least one flight engine (66) and a taxi engine (70) wherein all\' flight engines together provide, in total, a takeoff thrust (65) arranged in a takeoff thrust direction and the taxi engine provides a taxi thrust (75) which does not exceed 15% of the takeoff thrust and is directed substantially the same as the takeoff thrust direction. \rThe taxi thrust is thereby sufficient to taxi the aircraft along a taxi path. \rIn a system embodiment, the taxi thrust does not exceed 7.5% of the flight thrust. In another system embodiment, the flight engines have, in total, a flight engine weight and the taxi engine has a taxi engine weight that does not exceed 10% of the flight engine weight. In a system embodiment, the taxi engine weight does not exceed 7.0% of the flight engine weight. In another system embodiment, the taxi engine has a rated thrust and is configured so that the taxi thrust is within 40% -and 100% of the rated thrust. In another system embodiment, the taxi engine, includes a rotatable engine portion (80) to divert the taxi thrust over an azimuth angle (82) to assist taxiing along the taxi path. ";

Col0[50] = "The present invention uses an anatomically shaped bone graft contouring abutment in place of a conventional healing abutment to control the bone graft for optimal height. The extraction site aesthetics, in the form of enhanced gingival growth, are facilitated by the optimal bone graft placement. The inventive abutment includes a connection portion configured to connect to the dental implant. The inventive abutment also includes a body portion configured to mimic at least partially the anatomy of the extracted tooth. The body portion includes a front surface, a rear surface and two side surfaces, wherein each of the side surfaces includes a concavity configured to collect and contour bone graft material.";

Col0[51] = "The invention provides a system of generation of multi-channel analog output signals, from a single analog input signal, and the controlled activation of peripheral devices responsive to the multi-channel analog output signals. A single-channel to multi-channel analog-to-analog converter is provided to convert the single analog input signal to multiple output channels. Uni-directional coupling is used for coupling and mixing the multi-channel outputs and transferring the mixed outputs to a data buss. Signals on the data buss are used to drive the multiple peripheral devices.";

Col0[52] = "Apparatus, systems and methods related to sharpening blades for rotary cutters. In one illustrative embodiment, a power sharpener system secures a rotary cutting blade between upper and lower columns that form a rotating axle in contact with upper and lower sharpening stones, each positioned at an appropriate angle to contact a cutting edges of the rotary blade for sharpening. The upper column may be rotatably attached to an upper cover or lid and the lower column rotatably disposed in a base. After the rotary blade is secured, an electric motor is used to rotate the column, contacting the edges of the blade against the stones to simultaneously sharpen both edges of the blade. In some embodiments, a retractable plate may be disposed around the lower column for placement of the rotary blade thereon and a lifting lever may be used to facilitate blade removal.";

Col0[53] = "A window covering fastener useful for securing the edge of window covering material, such as an arched shade. The fastener includes a clip that slides over the edge of the material and is secured by a pin inserted into the clip to pass through the material. A bracket of the fastener is installed on the structure of or surrounding a window. The bracket and clip engage one another";

Col0[54] = "A mobile communication method according to the present invention includes: a step of transmitting, by an operation and maintenance server EM, \'MDT config\' \rto a radio base station eNB; a step of selecting, by the radio base station eNB, a target mobile station UE on the basis of the \'MDT config\'; a step of inquiring, by the radio base station eNB, of a mobility management node MME or a subscriber management server HSS \rabout whether the target mobile station UE is approved for performing an MDT \rmeasurement process; and a step of instructing, by the radio base station eNB, the target mobile station UE to perform the MDT measurement process when the target mobile station UE \ris approved for performing the MDT measurement process. ";

Col0[55] = "The present invention notifies of an EARFCN in an equivalent band by means of an SIB 5 while minimizing the increase in overhead. A mobile communication method according to the present invention includes: a step in which a radio base station eNB in a cell #1 notifies, by means of the SIB 5, of a band #2 and an equivalent band #21 that can be supported in a cell #2 adjacent to the cell #1; and a step in which a mobile station UE assumes that access in the cell #2 is prohibited when having determined that the mobile station does not support the band #2 and the equivalent band #21. ";

Col0[56] = "The addition and change of a CoMP transmission point performing a CoMP transmission/reception process is appropriately performed. A mobile communication method includes: a step of notifying, by a radio base station (eNB), configuration information of CSI-RS of a CoMP transmission point to a mobile station (UE) connected to a cell (#5) managed by the radio base station (eNB), when instructing an addition or change of the CoMP transmission point performing a CoMP \rtransmission/reception process by \'RRC Connection Reconfiguration\'; a step of measuring, by the mobile station (UE), a CQI of the CoMP transmission point by using the CSI-RS \rof the CoMP transmission point, while performing the CoMP \rtransmission/reception process; and a step of notifying, by the mobile station (UE), the CQI of the CoMP transmission point to the radio base station (eNB). ";

Col0[57] = "Provided is a radio base station and a mobile station capable of reducing a handover delay while avoiding an increase of a load on the C-Plane even in a case where the kind of the PDCP-SN used within a cell after the handover is changed. A \rradio base station eNB #1 according to the present invention includes a transmission unit 12 configured to notify a mobile station UE that the length of the PDCP-SN used in communication within the cell #11 (or the cell #1) is changed in a case where the mobile station UE performs a handover from the cell #1 to the cell #11 (or in a case where the mobile station UE performs a handover from the cell #11 to the cell #1). ";

Col0[58] = "An objective is to prohibit retransmission of \'UE \rassistance information\'. A mobile communication method according to the present invention includes the steps of: \rtransmitting \'UE assistance information\' to a radio base station (eNB) by a mobile station (UE), the \'UE assistance information\' prompting the radio base station (eNB) to change a parameter for the mobile station UE used in the radio base station; notifying, by the radio base station (eNB), the mobile station (UE) of a transmission-prohibited period of the \'UE \rassistance information\'; and stopping, by the mobile station (UE), retransmission of the \'UE assistance information\' on the basis of the transmission-prohibited period. ";

Col0[59] = "Light projection systems and methods may comprise combining light from two or more projectors. Each projector may be controlled so that the combined light output of the projectors matches a target for the projected light. In some embodiments optimization is performed to generate image data and control signals for each of the projectors. Embodiments may be applied in image projecting applications, lighting applications, and 3D stereoscopic imaging.";

Col0[60] = "Methods for fabricating metallic microneedles are disclosed. One method comprises providing a mold pillar; forming an apertured electrically-conductive layer over the mold pillar; and depositing a metal layer over the electrically-conductive layer to provide an apertured microneedle. Another method comprises providing a mold pillar; depositing a first metal layer over the mold pillar to provide a first microneedle; removing the first microneedle from the mold pillar; and depositing a second metal layer over the mold pillar to provide a second microneedle.";

Col0[61] = "The present invention relates in general to fishing lures, and more specifically, to a contracting fishing lure that provides life-like movement to mimic live bait. The fishing lure is configured so that when the fishing lure is retrieved (e.g., reeled in) or jigged by an angler, or the fishing line is pulled or twitched, the fishing lure transitions from a first non-contracted position to a second contracted position. The purpose of the invention is to provide a fishing lure that will successfully attract fish by displaying a unique action in the water.";

Col0[62] = "A method and system for fueling of a burner in a direct-fired device using syngas. A gasifier produces syngas from a carbonaceous feedstock such as biomass. The syngas is fed to a syngas burner. \rA booster burner disposed between the gasifier and the syngas burner increases the temperature of the syngas. The booster bunter may be provided with an approximately stoichiometric or sub-stoichiometric amount of oxidant. Operation of the booster burner may be regulated based on the temperature of the syngas. \rThe syngas burner may be used to direct-fire a device requiring a relatively high flame temperature, such as, for example, a lime kiln. ";

Col0[63] = "A window reveal kit can include a window, a first connector, and at least one reveal trim. The window has an outer side, an inner side, and a frame portion about a perimeter of the window. The first connector can be formed on the frame portion, on the inner side of the window. The at least one reveal trim can have a second connector that is configured to engage the first connector so that the reveal trim extends from the first connector.";

Col0[64] = "A burner (20) comprising: a first pipe section (30) having a discharge port (32) that discharges combustion gas formed therein; a second pipe section (40) that extends inside the first pipe section (30) towards the discharge port (32) and into which mixed air flows from the opposite side to the discharge port (32); a third pipe section (50) arranged inside the first pipe section (30), having the second pipe section (40) interpolated therein, and having an opening end positioned on the discharge port (32) side; a blocking section (51) that blocks the opening end; a coupling wall section (41) that blocks the gap between the first pipe section (30) and the second pipe section (40); a partitioning wall (55) coupled to the first pipe section (30) and the third pipe section (50) and having a communication path (56) formed in the partitioning wall (55) that communicates between the discharge port (32) side and the opposite side of the discharge port (32), relative to the partitioning wall (55); and an ignition unit (62) arranged on the discharge port (32) side relative to the partitioning wall (55), which ignites the mixed air.";

Col0[65] = "Power spring configurations for a spring energized fastening device includes a compact double torsion power spring and two opposed compact single torsion springs. Simplified structures to hold the springs in a stable pre-loaded position are disclosed. Each coil has forward extending arms including an angled portion and forward vertically coincident portions. The double torsion spring has a self-locking crossing geometry to hold a pre-loaded rest position. The opposed two springs have a bridge and a mandrel to hold the rest position. A lever presses arms of the spring between a striker and the coil including a compact nesting condition. A tab of the striker extends forward to provide a release edge and a positioning torque bias upon the striker.";

Col0[66] = "A fireplace assembly with an integrated burn control system includes a va-riety of features that provide an elegant, revo-lutionary, and highly-efficient way to heat a residence or other environment. The fireplace assembly may be used in combination with gas-burning fireplaces, stoves, and fireplace inserts. The fireplace assembly includes, but is not limited to: a control panel; a conceal-ment door that conceals the control panel when the concealment door is closed; \rauto-matic control panel lighting that is activated when the concealment door is open; a split flow or dual burner assembly that simulates a natural wood burning fire; and an intermittent pilot ignition system that allows a pilot flame to run continuously or intermittently. The fireplace assembly can be manually con-trolled via the control panel or automatically and/or remotely controlled via a remote con-trol device. ";

Col0[67] = "The present disclosure is directed to injectors with integrated igniters providing efficient injection, ignition, and complete combustion of various types of fuels. These integrated injectors/igniters can include, for example, multiple drivers used to shape charges, controllers used to modify operations based on ionization parameters, and so on.";

Col0[68] = "The present disclosure is directed to integrated injector/igniters providing efficient injection, ignition, and complete combustion of various types of fuels. One example of such an injectors/igniter can include a body having a base portion opposite a nozzle portion. The base portion receives the fuel into the body and the nozzle portion can be positioned adjacent to the combustion chamber. The injector further includes a valve carried by the nozzle portion that is movable between a closed position and an open position to inject the fuel into the combustion chamber. An actuator is coupled the valve and extends longitudinally through the body towards the base portion, and a driver is carried by the body and is movable between a first position and a second position. In the first position the driver does not move the actuator and in the second position the driver moves the actuator to move the valve to the open position.";

Col0[69] = "Embodiments of injectors suitable for injection ports having relatively small diameters are disclosed herein. An injector according to one embodiment includes a body having a first end portion opposite a second end portion. The second end portion is configured to be positioned adjacent to a combustion chamber and the first end portion is configured to be spaced apart from the combustion chamber. The injector also includes an ignition conductor extending through the body from the first end portion to the second end portion, and an insulator extending longitudinally along the ignition conductor and surrounding at least a portion of the ignition conductor. The injector further includes a valve extending longitudinally along the insulator from the first end portion to the second end portion. The valve includes a sealing end portion, and the valve is movable along the insulator between an open position and a closed position. The injector also includes a valve seat at or proximate to the second end portion of the body. When the valve is in the open position the sealing end portion is spaced apart from the valve seat, and when the valve is in the closed position the sealing end portion contacts at least a portion of the valve seat.";

Col0[70] = "A hoist mechanism for raising an animal carcass off the ground includes a pair of strap assemblies. Each strap assembly includes a first ratchet portion attachable to a support member and a loop assembly for grasping a portion of the animal carcass. A handle is provided on each ratchet strap to raise a portion of the carcass off the ground. By alternately raising different portions of the carcass a given distance above ground level, the carcass can ultimately be raised to a position where it can be positioned on a support surface, for example to a rack that is provided on a vehicle.";

Col0[71] = "A powered wheelchair 100 with a tilt mechanism having multiple pivots that allows the wheelchair 100 to be driven and steered with or without the use of hands. The wheelchair 100 has two spaced apart drive wheels 101, each mounted to a separate shaft 104 that is independent of the other drive wheel. A drive controller drivingly coupled to the shafts 104 and the drive controller is housed within a base 102 that is pivotally situated on the shafts 104. A seat 103 mounted on a tilt mechanism enables the seat to tilt in a forward, backward, left and right direction as a result of the user displacing their body weight in either of those directions. The tilt mechanism includes three pivots, a primary pivot P1, secondary pivot P2 and tertiary pivot P3. The primary pivot P1 pivotally connects the base 102 to the shafts 104. The secondary pivot P2 is situated above and adjacent the base 102 so that the respective ends of the rod 105 are pivotally connected to the base 102. The tilt mechanism and the drive controller are connected to a weight displacement sensor to control the movement and direction of travel of the wheelchair 100. Both the primary and secondary pivots P1 and P2 allow the seat 103 to pivotally move in a forward and backward direction (103F, 103B) relative to the wheels 101 and such movement is sensed by the weight displacement sensor that in turn causes the drive controller to impart drive to one or both of the drive wheels to move the wheelchair 100 in the sensed direction e.g. forward or backward. The secondary pivot P2 enhances the offset of weight transfer by a user so as to cause increased control of the back or forward tilt (103F, 103B) of the seat 103 relative to the shaft 104 which is not possible with just a primary pivot P 1 . The tertiary pivot P3 is situated above the secondary pivot P2 and is situated below and adjacent the seat 103 so as to pivotally connect the respective ends of the rod 105 to the seat. Tertiary pivot P3 allows the tilt mechanism to tilt the seat 104 in left and right directions (103R, 103L) and the weight displacement sensor upon sensing left or right movement causes the drive controller to impart drive to one or both of the drive wheels to turn the wheelchair 100 left or right.";

Col0[72] = "The invention relates to a method for ensuring the dimensional constancy of multisegment physical structures, in particular aircraft structures, during assembly, having the following steps: a spatially-fixed three-dimensional coordinate system (90) which encloses the subsequent assembled physical structure is set up; a plurality of segments (31, 32, 33) of the physical structure to be assembled are introduced into the spatially-fixed three-dimensional coordinate system (90) ; the positions of the individual segments (31, 32, 33) and of already assembled groups of segments (31, 32, 33) are recorded repeatedly within the spatially- fixed three-dimensional coordinate system (90) during assembly; and the position of a respective segment (31, 32, 33) or of a respective already assembled group of segments (31, 32, 33) is corrected if a respective record shows that the positions of the respective segment (31, 32, 33) or of the respective already assembled group of segments (31, 32, 33) is outside a tolerance band, which is predetermined in accordance with a desired dimensional constancy, by a respective predetermined nominal value.";

Col0[73] = "The present invention provides an apparatus and a method for producing a large-area fibre-composite structural component, in particular for the aircraft sector, comprising a predetermined shaping element (1) , a controllable laying device (4, 5, 6) for the defined laying of at least one fibrous sheet (15) over or into the predetermined shaping element (1) , a controllable turning device (10) for a defined turning of the predetermined shaping element (1) and of the laying device (4, 5, 6} in relation to each other by a predetermined turning angle, and a central control device, which is connected to the laying device (4, 5, 6) and the turning device (10) for controlling of the same.";

Col0[74] = "A leading end assembly for a movable partition may include a frame, an exterior skin coupled to the frame for covering a leading surface and two opposing side surfaces of the frame, the exterior skin including a leading member forming at least a portion of a leading surface of the leading end assembly and at least two side members, each side member being formed separately from the leading member and forming at least a portion of a lateral side portion of the leading end assembly. Movable partitions may include leading end assemblies and leading end assemblies may be formed by related methods.";

Col0[75] = "Multi-channel self-interference cancellation is provided in relayed electromagnetic communication (Fig. 4) between a first device and one or more other devices on one or more shared frequency channels. Specifically, near signals are generated at the first device and transmitted to a relay station. \rA composite signal is received at the first device from the relay station containing relayed versions of the near signals and relayed versions of remote signals transmitted from the one or more other devices, the composite signal having frequency channels including the one or more shared frequency channels, each shared frequency channel occupied by at least one of the relayed near signals and one of the relayed remote signals. One or more cancellation signals are selectively generated, each having a frequency band corresponding to one of the shared frequency channels. The cancellation signals are combined with the composite signal to produce a desired signal representing the relayed remote signals. ";

Col0[76] = "In a satellite or other relayed communication system having a plurality of subscriber terminals (ST 115) that communicate through an elevated wireless relay (typically a satellite (102) operating in bent pipe mode), a technique for subscriber terminal power control is provided whereby the power level is controlled via leader-follower operation relying on sharing control factors determined at a single calibrated subscriber terminal transmitter (the leader terminal) (103) to create traffic to be compared to the received traffic of the other subscriber terminals. The power level of the subscriber terminals is then adjusted based on the relationship of their received energy to the received energy of the leader terminal. ";

Col0[77] = "Methods, apparatuses, and systems are presented for deriving data from an error correction encoded composite signal involving (a) receiving a composite signal comprising contributions from a plurality of individual signals transmitted over different paths representing a common data sequence encoded using an error correction code, (b) calculating soft values of a first type taking into account the received composite signal and soft values of a second type, (c) generating symbol outputs taking into account soft values of the first type, (d) performing error correction decoding on the symbol soft outputs, (e) calculating soft values of the second type taking into account error correction decoded outputs , (f) feeding back soft values of the second type, (g) iteratively updating soft values of the first type, symbol outputs, error correction decoded outputs, and soft values of the second type by repeating previous steps, and (h) providing updated error correction decoded outputs. ";

Col0[78] = "A railcar hatch cover latching system including a sliding mechanism attached to a movable portion of the hatch cover and a latching apparatus associated with the hatch cover. \rThe latching apparatus has a biased assembly, a bar and at least one profiled stop. The bar extends through the biased assembly. The biased assembly is configured to allow the bar to pass through the biased assembly with a first force requirement. The at least one profiled stop is positioned on the bar to encounter the biased assembly and having a second force requirement to move the bar past the at least one profiled stop, the second force being greater than the first force. ";

Col0[79] = "An apparatus for setting a digital setpoint for a self-powered current sensing switch includes a current transformer, a digital processor and a parallel converter for converting the AC output of the current transformer to a DC power source for the digital processor along a first path and into a digital signal which is input to the digital processor along a second path. The apparatus also includes a manually operated switch coupled to the digital processor and having a calibration mode position, firmware executing on the digital processor to convert the digital signal to a digital setpoint value when the manually operated switch is in the calibration mode position, and non-volatile memory for storing the digital setpoint value.";

Col0[80] = "A direct current transducer includes an open-loop Hall-effect sensor, a first ADC coupled to the open-loop Hall-effect sensor, a thermistor, a second ADC coupled to the thermistor, a manually controlled mode-selection device, a digital processor coupled to the first ADC and the second ADC, and digital memory coupled to the digital processor. The manually controlled mode-selection device is operative to develop an operating mode selection digital signal for a plurality of operating modes including a temperature- compensated direct current (DC) transducer mode and a calibration mode.";

Col0[81] = "A hydraulic accumulator for a propellant tank in a spacecraft comprises an air guide tube (1), a cover plate (2), a housing (3), blades (4), a support column (5), a base (6), channel window pressing plates (7), channel window meshes (8), hydraulic accumulator meshes (9), a fixing block (10), and hydraulic accumulator mesh pressing plates (11). The blades (4) are uniformly distributed on and fixed to the support column (5) in a radial direction to form an integral structure, and the integral structure is mounted on and fixed to a circular partition plate in the base (6). The hydraulic accumulator meshes (9) are pressed on the circular partition plate in the base (6) by means of the hydraulic accumulator mesh pressing plates (11) and then are fixed. The channel window meshes (8) are pressed on the outer side of a cylinder wall of the base (6) by means of the channel window pressing plates (7) and then are fixed. The housing (3) is fixed at the top end of the base (6). The cover plate (2) is fixed on the housing (3). The fixing block (10) fixes the air guide tube (1) onto the cover plate (2). The hydraulic accumulator has a simple structure, high strength and reliability, a large liquid storage quantity and a wide work application range, has functions of repeatedly and circularly filling a liquid into the hydraulic accumulator and discharging the liquid from the hydraulic accumulator, has a high liquid filling rate and a high discharging rate, and accordingly, can implement ground repeated filling.";

Col0[82] = "A system (10, 10\') for cooling items of freight on board an aircraft includes a refrigerating device and also a cooling station (14, 14\') to which cooling energy generated by the refrigerating device is supplied by means of a refrigerant medium. The cooling station (14, 14\') is capable of being connected to a freight compartment (24) of the aircraft or to a freight container (261) on board the aircraft, in order to lead the cooling energy supplied to the cooling station (14, 14\') away into the freight compartment (24) or into the freight container (261). A freight container (261) for receiving items of freight designated for transportation on board an aircraft is capable of being connected to a cooling station (14\') of a system (101) for cooling items of freight on board an aircraft, so that the cooling energy supplied to the cooling station (141) is capable of being led away into the freight container (26\'). An alternative system (10\') for cooling items of freight on board an aircraft includes a refrigerating device that is capable of being connected to a cooling station (14\'), in order to supply cooling energy generated by the refrigerating device to the cooling station (14\') by means of a refrigerant medium. The cooling station (14\') is integrated into a freight container (26\') for receiving items of freight designated for transportation on board an aircraft and is set up to lead the cooling energy supplied to the cooling station (14\') away into the freight container (26\'). A corresponding freight container (26\') includes a cooling station (14\') integrated into the freight container (26\'), said cooling station being capable of being connected to a refrigerating device of a system for cooling items of freight on board an aircraft, in order to supply cooling energy generated by the refrigerating device to the cooling station (14\') by means of a refrigerant medium, said cooling energy being capable of being led away through the cooling station (14\') into the freight container (26\').";

Col0[83] = "The present invention relates to a wiring arrangement (50) for protecting a bleed air supply system (10) of an aircraft against overheating, the bleed air supply system (10) comprising a bleed air source (12), a bleed air feed (14), a shutoff valve (16) arranged in the bleed air feed (14) and a leakage monitoring device (38) with a monitoring control device (39), which is connected via a shutoff circuit (18) to the shutoff valve (16) in such a way that the shutoff valve (16) is closed when the shutoff circuit (18) is interrupted, it being provided that the wiring arrangement (50) comprises a thermal switch (52), which is connected in series with the shutoff valve (16) and the monitoring control device (39) to the shutoff circuit (18) and which, once a predetermined limit temperature (TG) has been exceeded, interrupts the shutoff circuit (18).";

Col0[84] = "Aircraft air-conditioning system (1) for an aircraft having a plurality of zones (2, 4), comprising a first line (6) for feeding cold air at an actual temperature T1act., a second line (14) which branches off a portion of the air from the first line (6) at a branching point (10) and feeds the air to a plurality of zones (2, 4) of an aircraft, wherein warm air is fed through a first trim valve (12) into the second line (14) so that the air in the second line (14) is heated to the actual temperature T2act., and a first zone feed line (24) feeding the air downstream of the first trim valve (12) to a first zone (2), wherein a second trim valve (26) is arranged in the first zone feed line (24), through which valve warm air is fed into the first zone feed line (24) so that the air in the first zone feed line (24) is heated to the actual temperature Tzf1act., and the first line (6) downstream and/or upstream of the branching point (1) feeds cold air at least to one further zone. A second feed line (18) feeds air downstream of the first adjustment (12) to a second zone (4). A heating device (20) can be arranged in the second feed line (18).";

Col0[85] = "An aircraft cooling system (1) according to the invention comprises a first coolant stream (4a) which cools at least one first heat load (2a), and a second coolant stream (4b) which cools at least one second heat load (2b), wherein the aircraft cooling system (1) is formed such that the first heat load (2a) and the second heat load (2b) are thermally coupled together. The first heat load (2a) and the second heat load (2b) are formed by two mutually redundant- aircraft components. A third coolant stream (12) can thermally couple the first heat load (2a) and the second heat load (2b) together. The third coolant stream (12) can be cooled by a heat sink (16).";

Col0[86] = "The present invention relates to a casement (1) for a glass window or a glass door, a frame and a window system containing a casement and a frame. The casement comprises an insulation material layer arrangement which is located between two wooden profile-members (3, 4). The insulation material layer arrangement has at least a first insulation layer (5) which is constructed for a high level of strength, and at least a second insulation layer (6) which is constructed for a high level of thermal insulation. Between the two wooden profile-members (3, 4), a lateral insulation layer (8) which is constructed for a high level of thermal insulation is arranged substantially perpendicularly relative to the extension direction of the insulation material layer arrangement. ";

Col0[87] = "A system (10) for reducing harmful substances in engine exhaust gases comprises a fuel cell (12), which is adapted to generate electrical energy and a steam--containing fuel cell exhaust gas during operation. A fuel tank (38) serves to store fuel which is to be supplied to an engine (44) during operation. A condensing device (32) is connected to an exhaust gas outlet (16) of the fuel cell (12) so that steam-containing fuel cell exhaust gas is supplyable to the condensing device (32). The condensing device (32) is adapted to convert the steam contained in the fuel cell exhaust gas into the liquid state of aggregation by means of condensation and to introduce the water obtained as a result of the condensing process into the fuel in order to form a water/fuel mixture. A water/fuel mixture line (96) is connected to the engine (44) so that a water/fuel mixture is supplyable to the engine (44). ";

Col0[88] = "Apparatus (10) for the material bed comminution of wet agglomerations, in particular wet coke, has a storage container for material to be comminuted, and a material bed roller mill (20). For efficient grinding, the storage container takes the form of a storage silo (12) having a discharge screw (14) which is moved in two dimensions, wherein the discharge screw (14) feeds the material to be comminuted from the storage silo (12) to a compressor screw (18) which is arranged directly upstream of the material bed roller mill (20) and has at least one discontinuous screw blade (30). ";

Col0[89] = "The invention relates to an air conditioner (10) comprising a fresh air line (12) connected to a fresh air inlet (14) for feeding fresh air to the air conditioner (10), and an adsorption device (16) disposed in the fresh air line (12) comprising an ad-sorption medium (18) for receiving moisture from the fresh air flowing through the fresh air line (12). ";

Col0[90] = "The invention relates to a jigsaw puzzle having at least two puzzle parts (10), of which each has an upper face (12), a lower face (14) and a circumferential edge (16), and a circumferential edge section (22, 23) which faces a circumferential edge section of the other puzzle part, and at least one connecting region (18) in the shape of a recess (19) or an extension (20), which is provided with at least one undercut (21) and is shaped so as to be complementary to the extension or the recess in a connecting region of the facing circumferential edge section of the respective other puzzle part. In order to stabilize a combination of puzzle parts, firstly each of the mutually facing circumferential edge sections on both sides of the connecting region and remote from the latter is provided with at least one circumferential edge piece (24), along which the course of the circumferential edge, seen in cross section, over at least part of the extent thereof between the upper face and the lower face, is defined by the bisector of a two-dimensional angle which is formed between two straight lines (alpha, beta) which intersect on the bisector and by an upper end point of the associated one of the mutually facing circumferential edge sections of the two puzzle parts to an upper end point of an opposite circumferential edge of the same puzzle part. Secondly, when puzzle parts are joined together along mutually facing circumferential edge sections, contact between the two puzzle parts occurs exclusively on said circumferential edge pieces and in the region of the or each undercut.";

Col0[91] = "A method of stiffening a rib (19, 20) during the assembly of an aircraft wing is described. A stiffener panel (40, 41) is attached to a face of the rib (19, 20). The rib is aligned with one or more wing components with the stiffener panel (40, 41) attached. An assembly operation such as drilling (16) is performed with the rib aligned and the stiffener panel attached. The stiffener panel (40, 41) is removed from the rib after the assembly operation. The stiffener panel has a resilient external sealing ring which is mounted on a face of the panel and forms an external perimeter of a vacuum cavity; and at least one resilient internal sealing ring which is mounted on the panel (20, 21) within the perimeter defined by the external sealing ring and forms an internal perimeter of the vacuum cavity. The stiffener can be attached to the rib by a vacuum clamping force, the vacuum being sealed by the external and internal sealing rings. The internal sealing ring(s) seal any holes which are present in the rib. The stiffener (40, 41) can support the rib (20, 21) during alignment to give it the required flatness. ";

Col0[92] = "The invention relates to a flow state sensor (10) for detecting a flow state at a body (16) that may be impinged on by a flow (12). A flow state sensor (10) that is of a simple construction and that is simple to evaluate is characterised in accordance with the invention by at least one frequency detecting device (20) for detecting at least one predefined frequency characteristic of the flow state. The frequency detecting device (20) has at least one oscillation element (22; 22a, 22b, 22c) excitable to resonant oscillatory movement (30) by a flow (12) and having a resonant frequency or natural frequency adapted to the predefined frequency characteristic, especially corresponding to the predefined frequency characteristic. Uses of the flow state sensor (10) in a flow measuring device (62) and in a flow measuring method, and an advantageous production method for the flow state sensor (10) are also proposed. ";

Col0[93] = "An overload detecting assembly comprising a lateral probe (18) which cooperates with a first load bearing member (10) as it moves towards a second load bearing member (11) and in turn deflects an indicator member (20) which may take a permanent set when a yield point is exceeded. Ready inspection of the indicator member reveals whether or not it has been bent. The indicator member may comprise a cantilevered beam (24) formed in a sleeve (20) coaxial with the load bearing members (10, 11). \rAlternatively, an extension (25) of the probe (18) may deflect laterally at a midpoint under overload conditions. Alternatively, the probe (18) may form an impression in an indicator member (30) under overload conditions. ";

Col0[94] = "A bearing assembly (2\') comprising a housing (3\') supporting first and second bearing ring portions (4, 4\') with bearing surfaces to engage an inner tubular member (1\') at axially spaced regions, characterised in that either: said bearing ring portions are provided by separate bearing rings (4\') supported in the housing member (3) with bearing surfaces of different diameters;\ror said bearing ring portions are provided by a single bearing ring (4\') that is free to flex radially and is supported so that the second bearing ring portion is free to flex radially under load and its bearing surface than assumes a position with a greater diameter than that of the first bearing ring portion (4\'). ";

Col0[95] = "A main landing gear assembly for an aircraft comprising: an elongate beam pivotally coupled about its longitudinal axis to the aircraft such that the axis of rotation of the elongate beam is generally parallel to the longitudinal axis of the aircraft fuselage; a shock strut pivotally coupled at a first end to the elongate beam and coupled at a second end to a wheel assembly; a folding forward stay pivotally coupled at a first end to the elongate beam and pivotally coupled at a second end to the shock strut; and a rigid rear stay pivotally coupled at a first end to the aircraft and pivotally coupled at a second end to the shock strut, the rigid rear stay being arranged to restrain the path of the shock strut when moving between a deployed and a retracted position such that the wheel assembly is located forward and inboard in the retracted position in comparison with its location in the deployed position.";

Col0[96] = "A landing gear (10), including: a bogie beam (12); an axle (14) pivotally connected to the bogie beam (12); a locking member (40) coupled to the axle (14) such that movement of the axle (14) invokes movement of the locking member (40), said movement of the locking member (40) defining a swept volume; and a locking mechanism (60) coupled to the bogie beam (12) and including first (65a) and second glide members, (65a, 65b) the locking mechanism (60) being arranged to move the glide members (65a, 65b) between locking positions, where glide members (65a, 65b) are within the swept volume on opposing sides of the locking member (40) and in which position the locking mechanism (60) is arranged to lock the locking member (40) in a predetermined position, and non- locking positions, where the locking mechanism (60) is arranged permit movement of the locking member (40).";

Col0[97] = "A remote data concentrator (RDC) for an avionics network, the RDC comprising an input/output interface (I/O) for connection to one or more input/output devices, and a network interface for connection to a remote processor, wherein the RDC is operable to provide communication between the input/output device(s) and the remote processor, and wherein the RDC further comprises a set of instructions for autonomously driving an output device connected to the I/O. Also, an avionics network including the RDC; an aircraft including the RDC; and a method of operating the RDC.";

export default Col0
