var lsz = 145;

var Col0 = Array([lsz]);

Col0[0] = "A method for configuring a voice authentication system comprises ascertaining a measure of confidence associated with a voice sample enrolled with the authentication system. The measure of confidence is derived through simulated impostor testing carried out on the enrolled sample.";

Col0[1] = "A novel compound, 1,2-dimethyl-4-dimethylaminomethyl-5-hydroxy benzimidazole, an agriculturally acceptable salt thereof, and an agriculturally acceptable solvate thereof, for crop enhancement is provided. Related compositions and methods are also provided.";

Col0[2] = "A nitrogen stabilizing composition is provided. The composition includes 10% to 18% w/w N-(n-butyl) thiophosphoric triamide (NBPT), a solvent, a light oil, and an emulsifier. Related methods for making liquid nitrogen stabilizing compositions, coated urea fertilizers and liquid urea fertilizer solutions are also provided.";

Col0[3] = "Designer Calvin-cycle-channeled and hydrogenotrophic biofuel-production pathways, the associated designer genes and designer transgenic organisms for autotrophic production of alcohols and biodiesel from carbon dioxide, hydrogen, and/or water are disclosed. The alcohols include methanol, ethanol, propanol, 1-butanol, 2-methyl-1-butanol, isobutanol, 3-methyl-1-butanol, 1 -hexanol, 1 -octanol, 1 -pentanol, 1 -heptanol, 3-methyl-1 -pentanol, 4-methyl- 1 -hexanol, - methyl-1-heptanol, 4-methyl-1-pentanol, 5-methyl-1-hexanol, and 6-methyl-1-heptanol. The designer autotrophic organisms such as designer transgenic oxyphotobacteria and algae comprise designer Calvin-cycle-channeled and hydrogenotrophic pathway gene(s) and biosafety-guarding technology for enhanced autotrophic production of alcohols and biodiesel from carbon dioxide and water; wherein the designer transgenic cells in their mass liquid culture can inducibly self-flocculate for enhanced harvesting of their biomass upon the expression of the designer cell surface-linked positively charged polypeptides. ";

Col0[4] = "The present invention regards oligonucleotides for modulating the expression of a gene, in particular for modulating a gene responsible for a pathology of genetic, tumoural or viral origin. Moreover, the present invention relates to the use of said oligonucleotides, possibly chemically modified, for the treatment and/or the diagnosis of said diseases.";

Col0[5] = "An insert type of cylinder cabinet cam lock permits use of Schlage-compatible deadbolt cylinders in a cabinet door and/or drawer cam lock. A bifurcated, housing is provided that journals a cam driver adapted for operational interconnection with the Schlage-compatible standard deadbolt.";

Col0[6] = "Compositions including a fuel soluble ferrocene compound and a fuel soluble solid carrier are disclosed. Methods of preparing tablet forms of the compositions are also disclosed. The fuel soluble ferrocene compound may be ferrocene and/or ferrocene derivatives. The compositions are useful for handling and rapidly solvating the fuel soluble ferrocene compound in a fuel such as gasoline.";

Col0[7] = "Methods and apparatus are provided for treating liquids containing solids. Liquid is introduced into the bore of a conduit having an injection site. The liquid has a flow direction in the bore and fills the bore at locations upstream of the injection site. Froth is injected into the liquid at the injection site. The injected froth disrupts the flow of the liquid and creates a froth-liquid mixture downstream from the injection site. The froth-liquid mixture exhibits turbulent flow in the flow direction and corresponding high-intensity mixing of the froth- liquid mixture. Solids may attach to surfaces of bubbles. The attachment of the solids may be promoted by the turbulent flow of the froth-liquid mixture and the corresponding high- intensity mixing. The froth may comprise a charged material that creates a charged environment which further promotes the attachment.";

Col0[8] = "A device for support and propulsion comprising a shaft, a spring element coupled to the shaft, and a swing arm coupled to the shaft and the spring element. A lower portion of the spring element comprises a ground interface, optionally comprising a wheel. ";

Col0[9] = "The invention relates to a support device 20 for at least one communication module 10. According to the invention, the support device 20 comprises: means for holding 201, in a removable manner, said communication module 10 intended to communicate with a communication terminal; means of fixing 202, in a repositionable manner, said support device 20 to said communication terminal.";

Col0[10] = "A preparation for topical application comprising glycerol and plant tannins, wherein the plant tannins have the capacity to bind to glycerol so that the glycerol has filmogen quality.";

Col0[11] = "The invention relates to a system for detecting an intrusion in an electronic device, the system comprising at least one optical sensor (C1) connected to at least one security module (MS) of the electronic device, the optical sensor and the security module being designed so as to detect a variation in light intensity measured by the optical sensor in relation to a reference light intensity associated with at least one predetermined light source (SL1) inside the electronic device, the variation in light intensity representing a risk of intrusion in the electronic device.";

Col0[12] = "A process for thermal hydrolysis of sludge, comprising: the pressurization of sludge to be treated (2) at a reference pressure between 2 bar a and 16 bar a, the injection of live steam (3) into said pressurized sludge so as to bring the temperature thereof to between 120°C and 200°C, the application to the sludge of a thermal hydrolysis cycle consisting in: a) conveying a sludge batch into a reaction space (7a, 7b, 7c); b) maintaining the sludge batch in said reaction space (7a, 7b, 7c) for a period sufficient for thermal hydrolysis thereof; and c) emptying said sludge batch out of said reaction space, the depressurization (10) of the hydrolized sludge and the discharge thereof (11), the application to the sludge of a thermal hydrolysis cycle being carried out in parallel in at least three reaction spaces (7a, 7b, 7c), in each of which a succession of treatment cycles is carried out, each of the reaction spaces being dedicated to the treatment of distinct sludge batches, steps a), b), and c) of said treatment cycles being offset in time from one reaction space to the other, a gaseous headspace common (12) to said at least three reaction spaces being controlled, and the pressure reigning in this common gaseous headspace being measured (15) and kept essentially constant at the reference pressure. A facility for carrying out this process.";

Col0[13] = "Apparatus that allows at least one feature of a patient\'s face to be observed while the patient is in a prone position includes a facial cushion, a video camera and a monitor. The facial cushion provides cranial support for a patient in a prone position during a medical procedure. The cushion has a frontal aperture that is dimensioned so that the facial feature of a patient wearing the facial cushion and in a prone position are visible through the at least one aperture. The video camera has a lens disposed for providing a sequence of video signals representing sequential images of the facial features that are visible through the frontal aperture. The monitor is coupled to the video camera for enabling the images of the at least one facial feature to be monitored. The images are monitored by a video monitor and/or a computer.";

Col0[14] = "Methods and apparatus relate to controlling location of inflow into a production well during in situ combustion. The production well includes intervals closable to the inflow at identified times. Once a combustion front from the in situ combustion passes one of the intervals, a blockage conveyed from surface into the production well forms a barrier to the inflow at the interval that has been passed by the combustion front. An example of the blockage includes a cement plug delivered through coiled tubing into the production well, which may include production tubing that defines the intervals based on at least two consecutive alternating lengths of solid wall sections and slotted or perforated sections of the production tubing.";

Col0[15] = "This invention relates to a method for sealing a breakthrough penetrating an injection well.";

Col0[16] = "Parametric Bayesian Updating method is described for attribute importance measures. AIM is a quantitative measure of the relative importance of multiple attributes used in a Bayesian Updating parametric multivariate modeling approach. The AIM is a function of the correlation coefficients between the attributes themselves and the attributes with collocated target variable. The importance calculation is straightforward, repeatable, and objective.";

Col0[17] = "The present invention relates to recovery of hydrocarbons being released subsea in an uncontrolled manner. More specifically, the invention relates to an apparatus, process and system for the recovery of well stream products being released subsea in an uncontrolled manner, optionally under conditions that are conducive to the formation of gas hydrate crystals.";

Col0[18] = "The present invention relates to cryogenic fluids. In another aspect, the present invention relates to additional protection of an apparatus containing equipment capable of operating at cryogenic temperatures and containing cryogenic materials. In one embodiment of the present invention, an apparatus includes: (a) a primary enclosure defining an internal volume, wherein the primary enclosure includes primary walls, a primary ceiling, a primary floor, and a vapor venting system, wherein the primary enclosure is fabricated from a low temperature alloy, wherein at least a portion of the primary floor forms a slope to a hydrocarbon outlet, wherein a perforated plate is located on top of the hydrocarbon outlet, wherein the perforated plate is fabricated from a low temperature alloy; and (b) a fire retardant agent applied to the exterior surface of the primary enclosure. ";

Col0[19] = "This invention relates to a method for sealing a breakthrough penetrating an injection well.";

Col0[20] = "A tool and method for safe extraction of a pig from the pig receiver of a pipeline enable removal of the pig by an operator standing fully clear of the opening of the pig receiver to avoid potential impact of the operator by the pig in the event of an inadvertent pressurized discharge of the pig from the receiver. The tool may feature one or more mechanisms for adjusting a reach-length of the tool in order to facilitate use on pig traps of different lengths with the same tool.";

Col0[21] = "The invention relates to the development of an analytical model to predict the velocity of the continuously expanding front of the steam chamber in a steam assisted gravity drainage (SAGD) hydrocarbon production system. The developed analytical model has advantages over reservoir simulation tool in that it is very fast and can be easily calibrated with field observation well data before making good prediction. One field study shows that the developed model can achieve excellent prediction for a field SAGD performance. A better understanding of the size of the steam chamber and the velocity of the front should provide better time, cost and energy efficiency for the production of high viscosity hydrocarbons.";

Col0[22] = "A system for the detection, containment and removal of hydrocarbon leaks in a subsea environment.";

Col0[23] = "A near-real-time tracking and integrated forecasting of marine ice bodies observable on satellite imagery. Oil and gas production operations in new regions, such as the Arctic, have dramatically increased over the past few years. This increasing activity makes it more likely that fixed or floating production platforms, drill ships, and other structures will be used in these regions. A concern for these types of structures in such regions is potential for damage caused by ice bodies that are uncontrolled and floating in the water, such as icebergs, ice floes, and other moving ice bodies";

Col0[24] = "Pyrazolopyridazine compounds and compositions comprising such compounds are provided. Methods of using such compounds and compositions for the treatment of retinal degenerative diseases, such as retinitis pigmentosa, Leber\'s congenital Amaurosis, Syndromic retinal degenerations, age-related macular degeneration and Usher Syndrome, and hearing loss associated with Usher Syndrome are provided. Some representative disclosed pyrazolopyridazine compounds share the general structure of Formula II shown below.";

Col0[25] = "Automated systems and methods for use in managing collections of capital assets determine optimal replacement dates for assets based on total cost curves. Replacement dates are adjusted within ranges that avoid unacceptable risk of unmonetizable failures to satisfy constraints. Priority in adjusting replacement dates is determined based on deferral cost metrics which may be based on the total cost curves.";

Col0[26] = "An anti-explosion and anti-fire system (5) is disclosed, system (5) comprising an encapsulant (20) disposed to cover high temperature surface portions (10) of a component (15); a conduit (25) in thermal connection with encapsulant (20); and a heat transfer fluid (30) disposed within conduit (25). A diesel engine (15A) is disclosed for an underground mine, engine (15A) comprising an encapsulant (20) disposed to cover high temperature surface portions (10) of a cylinder head (15B); a conduit (25) in thermal connection with encapsulant (20); and a heat transfer fluid (30) disposed within conduit (25). A method for encapsulating high temperature surface portions (10) of a cylinder head (15B) is disclosed, the method comprising positioning a conduit (25) adjacent head (15B); positioning an encapsulant (20) in thermal connection with head (15B) and conduit (25); and transferring heat from high temperature portions (10) to prevent gasses, coal dust, fuel, oils or other combustible material in an underground mine from contacting portions (10) at temperatures above an explosion or fire safety limit. ";

Col0[27] = "A method for producing a metal article according to one embodiment may involve the steps of: Providing a composite metal powder including a substantially homogeneous dispersion of molybdenum and molybdenum disulfide sub-particles that are fused together to form individual particles of the composite metal powder; and compressing the molybdenum/molybdenum disulfide composite metal powder under sufficient pressure to cause the mixture to behave as a nearly solid mass.";

Col0[28] = "A coated article system includes a substrate and a surface coating on the substrate. The surface coating is formed by depositing individual particles of a composite metal powder with sufficient energy to cause the composite metal powder to bond with the substrate and form the surface coating. The composite metal powder includes a substantially homogeneous dispersion of molybdenum and molybdenum disulfide sub-particles that are fused together to form the individual particles of the composite metal powder.";

Col0[29] = "Molybdenum disulfide powders include substantially spherically-shaped particles of molybdenum disulfide that are formed from agglomerations of generally flake-like sub-particles. The molybdenum disulfide powders are flowable and exhibit uniform densities. Methods for producing a molybdenum disulfide powder may include the steps of: \rProviding a supply of molybdenum disulfide precursor material; providing a supply of a liquid; providing a supply of a binder; providing a supply of a dispersant; \rcombining the molybdenum disulfide precursor material with the liquid, binder, and dispersant to form a slurry; feeding the slurry into a stream of hot gas; and recovering the molybdenum disulfide powder, the molybdenum disulfide powder including substantially spherically-shaped particles of molybdenum disulfide formed from agglomerations of generally flake-like sub-particles. ";

Col0[30] = "A method of removing ammonia from a gas stream may involve the steps of: Providing a primary slurry composition of a molybdic acid at a first pH; providing a secondary slurry composition of a molybdic acid at a second pH, the second pH being numerically lower than the first pH; atomizing the primary slurry composition in the presence of the gas stream to produce a partially processed gas stream, quantities of ammonia in the gas stream combining with the molybdic acid in the primary slurry composition to form a further concentrated primary ammoniated slurry composition; and atomizing the secondary slurry composition in the presence of the partially processed gas stream to produce a processed gas stream, additional quantities of ammonia in the partially processed gas stream combining with the molybdic acid in the secondary slurry composition to form a further concentrated secondary ammoniated slurry composition.";

Col0[31] = "Systems and methods are provided for cross-platform rendering of video content on a user-computing platform that is one type of a plurality of different user-computing platform types. A script is transmitted to the user-computing platform and is interpreted by an application program compiled to operate on any one of the plurality of user-computing platform types. Transmitting the script causes the script to be interpreted by the application program operating on the user-computing platform to cause the interpreted script to directly decode encoded video data transmitted or otherwise accessible to the user-computing platform into decoded video data and to further cause the rendering of the decoded video data.";

Col0[32] = "A method, an apparatus, a computer readable storage medium configured with instructions for carrying out a method, and logic encoded in one or more computer- readable tangible medium to carry out actions. The method is to decode audio data that includes N.n channels to M.m decoded audio channels, including unpacking metadata and unpacking and decoding frequency domain exponent and mantissa data; determining transform coefficients from the unpacked and decoded frequency domain exponent and mantissa data; inverse transforming the frequency domain data; and in the case M<N, downmixing according to downmixing data, the downmixing carried out efficiently. ";

Col0[33] = "A system for coating seeds with the composition containing a foaming agent and color indicator and related dispensing apparati.";

Col0[34] = "Imaging may be performed using a megavoltage (MV) radiotherapy treatment system. An electron beam directed at a low-Z target generates an imaging cone beam. The cone beam may be shaped to conform to projections of volumes of interest in a subject. Image fllling may be performed to reduce artifacts in the volumes of interest. Image data for filling may be derived from digitally reconstructed radiographs.";

Col0[35] = "A water vapour transport membrane comprises a nanofibrous layer disposed on a macroporous support layer, the nanofibrous layer coated with a water permeable polymer. A method for making a water vapour transport membrane comprises forming a nanofibrous layer on a macroporous support layer and applying a water permeable polymer to the nanofibrous layer. The water permeable polymer can be applied for so that the nanofibrous layer is substantially or partially filled with the water permeable polymer, or so that the coating forms a substantially continuous layer on one surface of the nanofibrous layer. In some embodiments of the method, the nanofibrous layer is formed by electro-spinning at least one polymer on at least one side of the porous support layer. In some embodiments, the support layer is formable and the method further comprises forming a three-dimensional structure from the water vapour transport membrane, for example, by compression molding, pleating or corrugating.";

Col0[36] = "A heat and humidity exchanger has example application in exchanging heat and water vapour between fresh air entering a building and air being vented from the building. The heat and humidity exchanger has a self-supporting core formed from layered sheets (710, 720) of a moisture-permeable material. Plenums (750) are arranged to direct fluid streams into and out of the core. The plenums (750) may be on opposing sides of the core to permit counterflow exchange of heat and water vapour. The plenums (750) are attached to the core along opposite edges of the sheets (710, 720).";

Col0[37] = "A downhole system has a plurality of telemetry systems and a control system configured to obtain information from one or more sensors and transmit that information on one or more of the plurality of telemetry systems. The configuration of a controller may be changed so as to change which information is transmitted on a given telemetry system and how the information is to be transmitted on the given telemetry system.";

Col0[38] = "An assembly for receiving telemetry signals from downhole equipment is located at a top end of a drill string above a drill rig floor. The assembly may be configured to receive multiple types of telemetry signals, for example, two or more of electromagnetic telemetry, mud pulse telemetry and drill string acoustic telemetry signals. The assembly may comprise a cap comprising a coupling and an end separated by an electrically-insulating gap region. The end of the cap may be connected to a grounding system for the drill rig.";

Col0[39] = "A housing for a mud motor is disclosed. The housing comprises a female member comprising a female mating section and a male member comprising a male mating section and a housing section. The male mating section is matingly received within the female mating section. The collar is positioned on the housing section. The collar is made up of a framework with a plurality of discrete bodies spaced about the framework and a portion of each of the discrete bodies protrudes above the framework.";

Col0[40] = "A mud hammer is driven by the flow of drilling fluid to generate pressure pulses. Timing and/or amplitude of the pulses are altered to encode data by applying electromagnetic forces to a movable member of the mud hammer. In an example embodiment the movable member carries one or more magnets and electromagnetic forces are applied to the movable member by one or more electromagnets. The mud hammer may also generate electrical power that may be applied to charge batteries and/or drive downhole electrical apparatus.";

Col0[41] = "This invention provides a method of promoting bone healing by locally administering a vanadium-based insulin mimetic agent to a patient in need thereof. The invention also provides a new use of insulin-mimetic vanadium compounds for manufacture of medicaments for accelerating bone-healing processes. In addition, the invention also encompasses a bone injury treatment kit suitable for localized administration of insulin-mimetic vanadium compounds or compositions thereof to a patient in need of such treatment.";

Col0[42] = "A reactor has two chambers, namely an oil feedstock chamber and a source chamber. An ion separator separates the oil feedstock chamber from the source chamber, wherein the ion separator allows alkali metal ions to pass from the source chamber, through the ion separator, and into the oil feedstock chamber. A cathode is at least partially housed within the oil feedstock chamber and an anode is at least partially housed within the source chamber. A quantity of an oil feedstock is within the oil feedstock chamber, the oil feedstock comprising at least one carbon atom and a heteroatom and/or one or more heavy metals, the oil feedstock further comprising naphthenic acid. When the alkali metal ion enters the oil feedstock chamber, the alkali metal reacts with the heteroatom, the heavy metals and/or the naphthenic acid, wherein the reaction with the alkali metal forms inorganic products.";

Col0[43] = "A process for upgrading an oil feedstock (102) includes reacting the oil feedstock (102) with a quantity of an alkali metal (106), wherein the reaction produces solid materials and liquid materials. The solid materials are separated from the liquid materials. The solid materials may be washed and heat treated (109) by heating the materials to a temperature above 400 C. The heat treating (109) occurs in an atmosphere that has low oxygen and water content. Once heat treated (109), the solid materials are added to a solution comprising a polar solvent, where sulfide, hydrogen sulfide or polysulfide anions dissolve. The solution comprising polar solvent is then added to an electrolytic cell (120), which during operation, produces alkali metal (106) and sulfur (128).";

Col0[44] = "An apparatus comprising a spring-biased translatable member extending through a collar; a gripping unit including a platform member attached to the translatable member, the platform member configured to receive an adhesive member; and a capture cone attached to an upper portion of the collar. In one version, the gripping unit includes an adhesive member configured to fit into a recessed area of the platform member. The adhesive member has a \'tacky\' surface for gripping and controlling a light bulb during removal and installation.";

Col0[45] = "A buyout management system includes a buyout processor to prepare a sponsor to conduct a buyout transaction and enable the sponsor to execute the buyout transaction upon the determination that the time is appropriate to do so. The buyout processor generates a readiness metric by applying a readiness ruleset to sponsor attributes. Using the readiness metric, an obtained quote from an insurer and attributes associated with the insurer, the buyout processor can generate a transaction readiness level that is compared to trigger thresholds. Upon the transaction readiness level meeting the trigger threshold, the buyout processor executes the buyout transaction.";

Col0[46] = "The invention is directed to a semi-solid food product metering device and method of operating a semi-solid food product metering device with at least two counter rotating feed rollers each with two ends, a distal end and a proximal end. An at least two feed rollers end plates contain the rollers with a first of the at least two roller end plates being a distal feed roller end plate at the distal end of the at least two counter rotating feed rollers and a second of the at least two roller end plates being a removable end plate at the proximal end of the counter rotating feed rollers with an at least one fastening device to fasten the at least two feed roller end plates in the operational position. An at least one frame support couples the at least two end plates, where the semi- solid food product metering device has a non-operational position and an operational position and is transitioned therebetween by a user, such that when in the operational position the semi- solid food product metering device is in operation and the at least one support bar supports the at least two feed roller end plates in the operating position with the at least one affixing device securing the end plates. When in the non-operational position, the device is not in operation, the affixing device is not securing the end plate and allows for movement, removal, or movement and removal of the second of the at least two end plates away from the end of the two counter rotating feed rollers to provide access to a gap between the at least two counter rotating feed roller ends and the two end plates in the non-operational position.";

Col0[47] = "Apparatus and methods for measuring the size of a round object are provided. Apparatus and methods for checking that a drop ball used in a well fracturing process has a predetermined diameter before being introduced into the wellbore are provided.";

Col0[48] = "A fastener is formed monolithically, or as a one-piece structure, for example 100% plastic. The fastener includes a body having first and second portions on respective sides of a positioning wall or stop means. A first portion includes a plurality of compressible retention surfaces separated from adjacent retention surfaces by a corresponding conical structure and a cylindrical surface on the body. A second portion includes a plurality of resiliently flexible tongues spaced apart from each other. The tongues may be positioned on opposite sides of the body from each other, and/or at different axial positions along the body.";

Col0[49] = "An improved oxidization process may be used to oxidize a wide variety of feedstocks.Oxidation takes place in a reactor where the feedstock is mixed with an oxidizing acid, such as nitric acid. The reaction mixture may also include a secondary oxidizing acid such as sulfuric acid as well as water and/or dissolved and mechanically mixed oxygen gas. The reactor may be maintained at an elevated pressure such as at least approximately 2070 kPa or desirably at least approximately 2800 kPa. The temperature of the reaction mixture may be maintained at no more than 210°C, In the various embodiments described herein, the process may include: combining recycled effluent from the reactor with the feedstock, combining one or more oxidizing acids with the feedstock, comminuting the feedstock to reduce the size of the particles, feeding the feedstock into the high pressure reactor at an approximately constant feed rate, dispersing oxygen gas from the headspace of the reactor into the reaction mixture, and/or removing all or almost all of the gas from the reactor through the liquid effluent. ";

Col0[50] = "An apparatus for detecting the occurrence of snow above a preset level in relation to a combustion device outlet vent and inflow fresh air inlet providing a remote signal and alarm activation response thereto. A sensor arranged to project a distance determinating beam indicates the presence of snow and obstructions to a controller that selectively activates a light and sound alarm. \rTelecommunication from the integrated alarm provides wireless notification to remote locations that an event has occurred and remedial action is required. ";

Col0[51] = "An apparatus for generating sets of radio parameters includes a first deriving unit deriving a set of radio parameters for specifying a symbol including an effective symbol part with the same period as the effective symbol part specified by another set of radio parameters and a guard interval part with a different period from the guard interval part specified by the other set of radio parameters. The apparatus further includes a second deriving unit deriving a set of radio parameters so that an occupancy proportion of the guard interval part in a single symbol specified by another set of radio parameters is equal to an occupancy proportion of the guard interval part in a single symbol specified by the other set of radio parameters.";

Col0[52] = "A mobile communication system is provided that performs bi-directional communications between a mobile station and a wireless access network device. The mobile station includes a connection set-up signal reception timing calculation unit for calculating a reception timing of a connection set-up signal when a connection request signal is transmitted, and a connection set-up signal reception determination unit that determines, according to the reception timing, whether the connection set-up signal is received, and performs a signal reception operation based on the determination. The wireless access network device includes a connection set-up signal scheduling unit that, after receiving a connection request signal from the mobile station, performs a connection set-up signal transmission assignment based on a reception timing of the connection request signal, a connection set-up signal generation unit that generates a connection set-up signal to be sent to the mobile station; and a connection set-up signal transmission unit that transmits the connection set-up signal based on the connection set-up signal transmission assignment. ";

Col0[53] = "The object is achieved by providing a transmission apparatus with: assignment means configured to assign, to each user, one of a frequency block that is obtained by dividing a system bandwidth into each block of continuous frequency subcarriers and a distributed type frequency block that include a frequency subcarrier that is discretely distributed in the system bandwidth; and mapping means configured to assign transmission data to one of the frequency block and the distributed type frequency block according to the assignment. ";

Col0[54] = "A disclosed transmission device includes a frequency scheduling unit configured to allocate, to each user, either frequency blocks that are consecutive frequency subcarrier blocks obtained by dividing a system bandwidth or distributed frequency blocks that are frequency subcarrier blocks discretely distributed in the system bandwidth; and a mapping unit configured to assign transmission data to the frequency blocks or the distributed frequency blocks according to the allocation result. The frequency scheduling unit is configured to allocate the distributed frequency blocks using the frequency blocks as units and to allocate sub-blocks obtained by dividing the respective distributed frequency blocks. ";

Col0[55] = "A base station decides a transmission interval and a radio resource of a scheduling request transmitted prior to transmission of uplink data by a mobile station device according to information indicating a state of the mobile station and/or service QoS information transmitted from the mobile station. The mobile station generates a scheduling request. According to the transmission interval and the radio resource, the mobile station performs transmission control of the scheduling request. The mobile station transmits a scheduling request. According to the scheduling request from the mobile station, the base station performs correlation detection and feeds back delay information to the mobile station. The mobile station holds synchronization according to the delay information transmitted from the base station.";

Col0[56] = "A transmission device is disclosed that includes a frequency scheduling unit configured to allocate resource blocks as a unit to each user, the resource blocks being blocks of consecutive frequency subcarriers divided from a system bandwidth, constitute a first group including consecutive plural resource blocks, constitute plural second groups, each including one or more resource blocks of the plural resource blocks constituting each first group, and allocate the resource blocks of either the first group or one or more the second groups; a mapping unit configured to allocate transmission data to the resource blocks in accordance with the allocation; and a control information generating unit configured to generate control information with respect to a mobile station to which either the first group or one or more the second groups are allocated. ";

Col0[57] = "User equipment that is capable of transmitting at least an uplink control channel to a base station apparatus using a single carrier method and to which persistent scheduling is applied, the user equipment includes a unit providing data arrival acknowledgement information, a unit providing channel quality information, a control channel generation unit generating an uplink control channel including at least one of the data arrival acknowledgement information or the channel quality information, and a transmission unit transmitting the uplink control channel using a predetermined dedicated bandwidth, in which the uplink control channel includes at least one unit block including a sequence in which a same factor reported using an upper-layer signaling is multiplied to each chip of an orthogonal code sequence for the user equipment. ";

Col0[58] = "A radio access network apparatus is disclosed. The apparatus communicates with a mobile station using a dedicated uplink channel, a downlink shared data channel, and a downlink signaling control channel. The apparatus includes a dedicated uplink channel allocating unit which allocates, to a mobile station starting or restarting communications, on a downlink shared data channel, a dedicated uplink channel to be used by the mobile station; \ra dedicated channel reception detecting unit which detects, on the allocated dedicated uplink channel, a reception of an uplink transmission from the mobile station; and a downlink transmitting unit which, when the dedicated channel reception of the mobile station is detected, transmits a response to the mobile station using the downlink shared data channel and the downlink signaling control channel. ";

Col0[59] = "A base station apparatus in a radio communications system is disclosed. The base station apparatus communicates with a mobile station using an OFDM scheme in downlink. The base station apparatus includes a sync signal generating unit which generates a secondary sync channel; a multiplying unit which multiplies a scramble code with the secondary sync channel; and a transmitting unit which transmits the secondary sync channel with which the scramble code is multiplied. Cell-specific information is detected by the secondary sync channel.";

Col0[60] = "A user equipment terminal for selecting a standby cell based on a specified priority of cell selection includes a determining unit configured to receive a signal transmitted from a base station apparatus and determine whether priority information of cell selection is included in the signal; and a cell selecting unit configured to perform, based on the determination result by the determining unit, cell selection with a same priority for each cell, when the priority information is not included. ";

Col0[61] = "A base station apparatus is disclosed for use in a mobile communication system including multiple cells having multiple sectors. The base station apparatus includes a synchronization channel generation unit configured to generate a synchronization channel for use in cell search by a user apparatus and a transmitting unit configured to wirelessly transmit a signal including the synchronization channel. The synchronization channel includes a primary synchronization channel and a secondary synchronization channel. The primary synchronization channel includes multiple types of sequences, and the secondary synchronization channel transmitted in a sector of a cell includes a code derived from a predefined generation polynomial equation corresponding to the primary synchronization channel. ";

Col0[62] = "Multiple reference signal transmission bandwidths are defined for system frequency bands and hierarchical reference signal bandwidths are defined for each reference signal transmission bandwidth such that a reference signal bandwidth lower than a highest-order reference signal bandwidth is a division of a higher-order reference signal bandwidth. A base station stores reference signal bandwidth information indicating the hierarchical reference signal bandwidths for each system frequency band; broadcasts the reference signal bandwidth information corresponding to a reference signal transmission bandwidth used by the base station; \rsets a frequency hopping bandwidth for a reference signal; reports, to a user device, the frequency hopping bandwidth and a reference signal bandwidth as assigned reference signal transmission bandwidth information; \rsets a reference signal transmission frequency band within the frequency hopping bandwidth based on the reference signal bandwidth information and the assigned reference signal transmission bandwidth information; and receives the reference signal from the user device. ";

Col0[63] = "A user apparatus including at least operation modes of a connection mode and an idle mode, includes: a measurement unit that measures radio quality in the idle mode according to measurement target information (Config#m, Config#n) indicating that the user apparatus is set beforehand to report a measurement value of radio quality to a management node; a storage unit that stores the measurement target information and the measurement value of radio quality measured by the measurement unit; and a transmission unit that transmits, in the connection mode, an indicator indicating that there is the measurement value of radio quality to the management node, and transmits a report signal including the measurement value of radio quality to the management node according to a request from the management node, wherein, when the user apparatus obtains new measurement target information (Config#n), the storage unit stores the new measurement target information according to a predetermined updating rule (reconfiguration model). ";

Col0[64] = "A paging method of the present invention is a paging method for paging a UE (10) in an idle state when a P-GW (20) receives a packet for the UE (10) and includes the steps of: in a S-GW (30), setting reception type information of the packet received by the P-GW (20) in \'Downlink Data Notification\' and sending the \'Downlink Data Notification\' to an MME (40) and an SGSN (60), and in the MME (40) and SGSN (60), determining whether or not to page the UE (10) based on the reception type information included in the \'Downlink Data Notification\' from the S-GW (30). ";

Col0[65] = "The purpose of the present invention is to provide a wireless base station device, a mobile terminal device and a wireless communication method capable of coping with interference from other cells, regardless of whether an inter-cell coordination technology such as CoMP is considered. This wireless communication method is characterized in that: with regard to a wireless base station device, notification information, which includes subframe information for a local cell and subframe information for other cells, is generated, and the notification information is transmitted to mobile terminal devices that are using the local cell as the serving cell; and with regard to a mobile terminal device, the notification information, which includes subframe information for the serving cell and subframe information for other cells, is received, and the channel quality of the serving cell is measured using the subframe information for the serving cell, and the channel quality of the other cells is measured using the subframe information for the other cells.";

Col0[66] = "The present invention is designated to reduce the deterioration of transmission characteristics upon data transmission, even when soft buffer memory for retransmission control is not sufficiently secured in a mobile terminal apparatus. The present invention provides the steps of, in a base station apparatus (eNB), performing channel coding of information bits (ST 802), performing a rate matching process for the coded bits after interleaving (ST 804), and transmitting transmission data to match the coded bit length after rate matching, to a mobile terminal apparatus (UE) (ST 806), and, in the mobile terminal apparatus (UE), receiving the transmission data (ST 807), performing channel decoding of the received data (ST 810), and discarding part of the received data in accordance with the size of the soft buffer memory in the mobile terminal apparatus (UE) and storing this in the soft buffer memory (ST 812 and ST 813). ";

Col0[67] = "A process and apparatus are provided in the present invention for treatment of particulate biomass. The present process comprises a densification stage, a first treatment stage, a second treatment stage, a cooling stage; the present apparatus comprises a thermo-chemical treatment chamber which is a two-stage compact moving bed type including two compartments for pre-torrefaction and torrefaction and having a star or spider or ring formic hot gas distribution system equipped with at least one hot gas input and at least one hot gas output for each compartment, and at least one particulate biomass inlet and at least one particulate biomass outlet. ";

Col0[68] = "An assembly for adjusting the position of a load for a backpack has a supporting member (3), an actuating means (35), and a plurality of elongate flexible movable members (7). Each of the elongate flexible movable members are attached to a load carrying portion (1) at one end, and attached to the actuating means at the second end. The load carrying portion is movable between: a retracted position, in which the load carrying portion abuts the supporting member, when the actuating means is moved into a first position; and an extended position, in which a user can freely move the load carrying portion relative to the supporting member, when the actuating means is moved into a second position.";

Col0[69] = "The invention relates to a handling system (100) of objects (133) between a transferring star (130) and a rotary machine (1) comprising a plurality of processing units (10), wherein said transferring star (130) comprises along its perimeter (136) a plurality of seats (134) for housing said objects, said processing units (10) being spaced apart by a first pitch (150) along a first circumference (155) and said seats (134) being spaced apart by a second pitch (131) along a second circumference (136),wherein said second pitch (131) is different from said first pitch (150) and wherein said circumferences (155, 136) are not tangent, said handling system (100) comprising a gripping unit (112)for each processing unit (10), said gripping unit (112) comprising a gripping nipper (103) suitable for gripping said object (133); means of moving (102,202) said gripping nipper (103) suitable for alternatively moving said nipper (103) between a first radial position, at the processing unit (10) and a second radial position at a seat (134) of the transferring star (130). ";

Col0[70] = "A stud end link comprises a main body having first and second openings and a swivel ball bushing. The first opening and swivel ball each have truncated spherical surfaces to allow the swivel ball to be seated within the first opening, while permitting the swivel ball to pivot a limited amount about a lateral axis within the first opening. The first opening includes a slot to facilitate installation and removal of the swivel ball. In some implementations, the swivel ball includes a tab which matingly fits within the slot to prevent rotation of the swivel ball about an axis perpendicular to the main body.";

Col0[71] = "A process for removing aluminum and other metal chlorides from liquid chlorosilanes with the steps of: introducing a source of seed into a source of impure liquid chlorosilanes, initiating the crystallization of aluminum and other metal chlorides on the seed from the liquid chlorosilanes in a first agitated vessel, passing the resulting mixture of liquid and solids through a cooler into a second agitated vessel for additional crystallization, transferring the resulting mixture of liquid and solids into a solids removal device, transferring the liquid with reduced solids content to a further process or vessel and transferring the liquid with high solids content into a waste concentration device, passing the resulting liquid with reduced solids content to a further process or vessel and passing the resultant liquid with very high solids content to a waste storage vessel with agitation. ";

Col0[72] = "An improved safety hypodermic syringe includes a reciprocal tubular needle sheath disposed on the exterior of the syringe body, a latch mechanism engaging the syringe body and the sheath to latch the sheath in a needle-covering position after delivering contents from the syringe body, and a spring engaging the syringe body and the sheath and expandable to move the sheath to cover the needle point, where the spring is a non- uniform helical spring having multiple 360° turns each turn uniformly spaced from adjacent turns, each 360° turn comprising first and second alternating angled portions, the first of the alternating angled portions being at a first angle to a plane perpendicular to an axis through the center of the helical spring and the second angled portions being at a second lesser angle to the plane perpendicular to the axis. ";

Col0[73] = "A dual wall axial flow electric heater for leak sensitive applications provides an improved corrosion and leak resistant assembly and includes protective tubes over electrical heater rods, double tube-sheets spaced apart by a plenum and leak detectors positioned to sensor leaks through the walls of the protective tubes. The design includes the option of two or more tube bundles with each inserted into opposite ends of a shell surrounding the tube sheets and heaters. The design provides ease of maintenance since each heater rod can be replaced independently while the unit is in service. Variable heat flux is provided from standard single flux heater rods by providing protective tubes of varying diameters.\r A built-in thermowell is provided to allow the rod temperatures to be monitored directly. Hot spots are avoided by the use of turning baffles and vibration is avoided by use of spider baffles to support the tubes. ";

Col0[74] = "The present invention is a sheave assembly that includes a ring supported by a support assembly instead of a solid sheave wheel supported by a central axle. The support assembly may include a plurality of rollers or a curved shoe. The ring is made of a lubricated plastic material or other similar material. The ring includes a groove for retaining the wireline or cable and an inner surface that is designed to mate with the outer surface support assembly.";

Col0[75] = "A process for manufacturing a non-woven fabric having on its surface distributed elements having a physical dimension, comprises screen printing on wet fabric a desired shape using a paste that expands under heating by virtue of a puffing agent contained therein.";

Col0[76] = "An access door for insertion into an opening in a construction surface is provided. The access door has a frame for engagement with edges of the opening in the construction surface. The frame has a channel formed therein for receiving a thermally insulative material to provide a thermal break between the frame and the construction surface. A door is operatively coupled to the frame and movable between an open position allowing access through the opening in the construction surface and a closed position preventing access through the opening in the construction surface.";

Col0[77] = "A clip-in access door for covering an opening in a construction surface has a frame for mounting in the opening, a door mounted on the frame, and a plurality of clips mounted on the frame for securing the frame in the opening of the construction surface. The clips along at least one edge of the frame are rotatable between an insert position and a lock position. \rMethods of using the clip-in access door are provided. ";

Col0[78] = "A power take off coupling for connecting an engine (20, 21) to a site accessory (16, 14, 17), comprises a resilient power transmission component (3) within the coupling; a latching device (8, 46, 9) to mechanically latch the accessory to the engine (20, 21), with a manually operable release handle (13) to effect unlatching. A power output shaft of the engine (20, 21) carries one half (5) of a dog clutch with the other half (7) carried by the accessory (16, 14, 17). An alignment arrangement comprises a first annulus ring (18) attached coaxiaily to an output shaft assembly of the engine (20, 21 ), and a second annulus ring (19) attached coaxiaily to an input shaft assembly of the accessory, with the two rings (18, 19) being of different diameters, such that one ring is adapted to be engaged coaxiaily within the other ring with close tolerances, such that the external periphery of the smaller ring (18) engages at least parts of the internal periphery of the larger ring (19) to provide for accurate coaxial alignment of the power output shaft of the engine (20, 21) and the power input shaft of the accessory.";

Col0[79] = "An LED lamp uses a flexible metal belt as a heat sink. At least one light emitting diode is attached to a circuit board that is mounted on a heat conducting member. The flexible heat sink is attached to the heat conducting member, such that heat generated by the light emitting diode and circuit board is conducted to the flexible heat sink. The flexible heat sink can be deformed to flt in a variety of spaces. The flexible heat sink dissipates the heat generated by the LED lamp without the need for a fan. The flexible heat sink may be made from braided copper fabric or even a plurality of flexible metal sheets.";

Col0[80] = "A mobile communication method includes the steps of: \rtransmitting, from a radio base station (eNB) to a mobile station (UE), a measurement rule designation command which designates addition or deletion of a measurement rule; \rtransmitting, from the radio base station (eNB) to the mobile station (UE) , a measurement object designation command, which designates addition or deletion of a measurement object, independently from the measurement rule designation command; \rand transmitting, from the radio base station (eNB) to the mobile station (UE), a mapping designation command which designates associating of the measurement object with the measurement rule. ";

Col0[81] = "When, using a handover request message of a mobile station (UE), a handover source radio base station (S-eNB) notifies a radio base station (T-eNB) whether or not user plane data to be transferred to the radio base station (T-eNB) is present on each access bearer set between the radio base station (T-eNB) and an upper-level node (SGW), the radio base station (T-eNB) sets a data transfer tunnel for transferring the user plane data for only an access bearer on which the user plane data to be transferred is present. ";

Col0[82] = "A mobile communication method according to the present invention includes the steps of: (A) calculating, at the radio base station (eNB1), an estimated neighbor radio base station parameter, on a basis of load information acquired from a neighbor radio base station (eNB2), the estimated neighbor radio base station parameter being supposed to be used in the neighbor radio base station (eNB2); and (B) notifying, from the radio base station to (eNB1) the neighbor radio base station (eNB2), the estimated neighbor radio base station parameter. ";

Col0[83] = "A radio base station according to the present invention comprising : a mobile communication system, a relay node and a radio base station are connected via a radio bearer, a mobile station is configured to conduct a handover process between the state in which a radio bearer is set with the relay node in order to communicate via the relay node and the radio base station, and the state in which a radio bearer is set with the radio base station in order to communicate via the radio base station, and the mobile station is configured such that during the handover process, control signals involved in the handover process are sent and received via a radio bearer between the relay node and the radio base station. ";

Col0[84] = "A radio base station according to the present invention comprising: \ra mobile communication system configured to transmit and receive a data signal between a mobile station and a gateway device via a relay node and a radio base station, wherein the mobile communication system is configured such that the radio bearer for the mobile station is set between the mobile station and the relay node, the radio bearer for the relay node is set between the relay node and the radio base station, a network bearer for the mobile station is set between the relay node and the gateway device, the network bearer for a plurality of mobile stations is multiplexed in the radio bearer for the relay node; \rand a data signal is transmitted and received between the mobile station and the gateway device via the radio bearer for the mobile station and the network bearer for the mobile station. ";

Col0[85] = "A radio base station according to the present invention comprising : a mobile communication system, a first relay node and a radio base station are connected via a radio bearer, a second relay node and a radio base station are connected via a radio bearer, a mobile station is configured so as to conduct a handover process between a first state wherein a radio bearer is established with the first relay node in order to communicate via the first relay node and the radio base station, and a second state wherein a radio bearer is established with the second relay node in order to communicate via the second relay node and the radio base station and the mobile station is configured such that in the handover process, control signals involved in the handover process are transmitted and received via the radio bearer between the first relay node and the radio base station, and via the radio bearer between the second relay node and the radio base station. ";

Col0[86] = "Even when radio base stations including radio base station identification information eNB IDs having different lengths are coexistent, it is possible to perform an S1 handover. A mobile communication method according to the present invention includes a step of determining, a handover source radio base station eNB#0, whether a handover destination candidate radio base station is a macro cell radio base station eNB or a small cell radio base station HeNB with reference to a predetermined bit set in Cell ID included in E.CGI included in Measurement Report received from a mobile station UE. ";

Col0[87] = "A mobile communication method according to the present invention includes a step A in which, in location registration processing of a mobile station, an switch of a first communication scheme and an switch of a second communication scheme send a subscriber information server first information used to determine whether or not all coverage areas have a same capability of providing a telephony service by packet switching; and a step B in which, when a status inquiry request made upon receipt of a terminating-call signal destined for the mobile station is received from an application server, the subscriber information server determines based on the first information whether or not to make an inquiry at the switch of the first communication scheme or the switch of the second communication scheme about whether or not provision of the telephony service by packet switching is possible in an area where the mobile station is located. ";

Col0[88] = "The disclosed mobile station (UE) is equipped with: measurement units (102) that measure the wireless quality of a currently communicating cell or a neighboring cell for each carrier among at least two carriers; a determination unit (104) that determines whether or not the wireless base station (eNB) should be notified of the measurement results of the measurement units (102) for each carrier among the at least two carriers; and a transmission unit (106) that transmits the measurement results of the measurement units (102) to the wireless base station (eNB) when the determination unit (104) has determined that the wireless base station (eNB) should be notified of the measurement results of the measurement units (102). Along with the measurement results relating to the carrier for which it has been determined by the determination unit (104) that the wireless base station (eNB) shall be notified of the measurement results of the measurement units (102), the transmission unit (106) transmits measurement results relating to carriers other than said carrier.";

Col0[89] = "A mobile communication method according to the present invention includes a step of notifying, by a radio base station DeNB, a radio base station eNB of identification information (PCI or ECGI) of cells #1 to #3 subordinate to a plurality of relay nodes RN#1 to #3 as identification information of a cell subordinate to the radio base station DeNB when the plurality of relay nodes RN#1 to #3 are connected to the radio base station DeNB. ";

Col0[90] = "The present invention relates to a mobile communication method that sends and receives the signaling of an S1AP/X2AP layer on DRB established between a radio base station DeNB and a relay node RN, the mobile communication method including: a step of setting the above DBR in an attach process of the relay node RN; and a step of notifying the above DRB to the relay node RN and the radio base station DeNB in an attach process of the relay node RN. ";

Col0[91] = "To provide a scheme for deciding a switching method for the video call when an UE#1 in video call with an UE#2 is caused to perform handover from an E-UTRAN to a UTRAN/GERAN. A mobile communication method according to the present invention is summarized by including the steps of: deciding the switching method for the video call, when a video bearer and a voice bearer which configure a path for the video call are set, by an INS; and maintaining information on the decided switching method and association information with which information on the video bearer is in association with information on the voice bearer, by a mobile communcation network and an eNB. ";

Col0[92] = "A base station device eNB according to the present embodiment is equipped with a capability signal receiver (202) configured to receive, from a user device UE, a capability signal for notifying whether the user device has an ability to transmit an uplink signal simultaneously in an assigned non-continuous frequency range The capability signal is configured so as to provide a notification for every operating band.";

Col0[93] = "To enable control such that a roaming mobile station UE is not instructed to perform MDT. A mobile communication method according to the present invention includes: a step of determining, by a mobile management node MME, whether a mobile station UE is a roaming mobile station UE (Roaming User), in an Attach procedure of a mobile station UE or a transition procedure to an Active state; and a step of transmitting, by the mobile management node MME, to a radio base station eNB, \'User Consent Indication\' indicating that the mobile station UE has not given consent for implementation of MDT when it is determined that the mobile station UE is a roaming mobile station UE. ";

Col0[94] = "In MDT, a radio base station eNB reports, to an operation and maintenance server OAM, location information of a mobile station UE \rand a QoS measurement result in an exactly associated manner. A \rmobile communication method according to the present invention includes a step of reporting, by the mobile station UE, \'MDT \rMeasurement\' and \'Location Information\', to the radio base station eNB, and a step of recording, by the radio base station eNB, the \'Location Information\' in addition to \'DL Throughput\' at an \'Active Time\' and \'MDT Measurement\' when the \'Location Information\' is received during the \'Active Time\', and reporting the \'DL Throughput\', the \'MDT Measurement\', and the \'Location Information\' to the operation and maintenance server OAM. ";

Col0[95] = "The mobile station (UE) according to this invention is provided with a control unit (12) that is configured to deactivate Scell#2 when the mobile station (UE) is instructed to modify the TAG containing Scell#2 from TAG#2 to TAG#1.";

Col0[96] = "Setting of transmission of \'UE assistance information\' is conducted suitably. A mobile communication method according to the present invention includes the steps of, when an attach process of a mobile station UE is conducted, causing a radio base station eNB or a mobility management node MME to transmit an information element indicating whether it is suitable to transmit \'\'UE \rassistance information\' that urges a change of parameters for the mobile station UE used in the radio base station eNB, to the mobile station UE, and causing the mobile station UE to determine whether it is suitable to transmit \'UE assistance information\' to the radio base station eNB, on the basis of the information element. ";

Col0[97] = "An objective is to appropriately select a \'timing reference cell\' and a \'Pathloss reference cell\' for an Scell in an sTAG. A mobile station UE according to the present invention includes a second management unit 11B configured to use a \'UL Cell\' managed in association with a \'DL only Cell\' \rwhere to perform a downlink communication only, as a Pcell or an Scell in a pTAG. ";

Col0[98] = "The present invention realizes an appropriate \'idle mode cell reselection\' by changing a threshold value that is used when performing \'idle mode cell reselection\' in a case where RSRQ measurement is performed for a six resource block and in a case where \'wideband RSRQ measurement\' is performed. This mobile communication method has a step in which a wireless base station (eNB) or a wireless link control station (RNC) reports an existing parameter used when performing cell reselection processing on the basis of RSRQ measurement results for a six resource block, and a wideband parameter used when performing \'idle mode cell reselection\' on the basis of measurement results by \'wideband RSRQ measurement\'.";

Col0[99] = "Methods of modular building construction are provided. One method includes (a) providing a first volumetric construction module comprising a frame, the frame including a first segment; (b) defining a volume of a composite segment and integrating the first segment with the volume; and (c) filling the volume with a curable material to cast the composite segment. Related methods, components, buildings incorporating such components, and methods of manufacture of components are also provided.";

Col0[100] = "Undesirably high energy-consumption in illuminating devices can be caused at least in part by wasted (attenuated) light. Optically efficient illumination systems that may be used to project light, including images, use light redirection. Phase modulating devices may be applied to create desired light fields. Some embodiments provide dual or multiple modulation display or projection systems in which some or all of the modulators not only attenuate amplitude, but also amplify amplitude, or change the phase, frequency and polarization of the light provided by the light source. ";

Col0[101] = "A free-form lens (for example a phase modulator, lens or deformable mirror) may be made to reproduce a light pattern specified by image data. Source regions on the free-form lens are mapped to target regions areas on an image. Areas of the source regions are adjusted to vary the amount of light delivered to each of the target regions. \rAdjustment of the source areas may be achieved using a L-BFGS optimization which preferably incorporates smoothness and curl regularizers. Embodiments apply parallel processing to obtain control values for a free form lens in real time or near real time. Apparatus may process image data and display an image by controlling a dynamically variable free form lens using the processed image data. ";

Col0[102] = "An apparatus for skin imaging is provided. The apparatus is used in conjunction with a mobile device to obtain digital images using a digital camera and a light source provided by the mobile device. The apparatus includes an optical system for illuminating an object to be imaged with uniform ambient light and a light conduit for delivering reflected light to the mobile device digital camera. The apparatus is removably attachable to the mobile device and/or a mobile device case. One or more optical elements, such as lenses, films, filters, and light caps may be used to improve image quality and/or acquire magnified images.";

Col0[103] = "A bioprocess comprises regulating pH of trade effluent wastewater, adding and mixing a first bio-additive, adding and mixing a flocculant /coagulant, filtering through a filter device, adding, mixing of a second bio-additive with aeration, and adding and mixing of a third bio-additive with aeration. \rTreatment can be discontinued or continued by adding and mixing of hydrogen peroxide with aeration, and optionally exposing treated effluent to UV disinfectant. The treated effluent can be recycled or disposed. \rCompositions of bio-additives 1, 2 and 3 comprise a group of highly selective and effective microorganisms and enzymes that are immobilized on carrier support matrices from a group of alginate, chitosan, polyacrylamides, k-carrageenan and agarose. ";

Col0[104] = "A method for removing metal contaminants from acidic mine wastewater using lignin derivatives, such as lignosulfonates and kraft lignin, an alkali coagulant, such as a lime compound, and an alkaline composition for increasing the pH. The lignin derivatives are dispersed in the wastewater and the coagulant is added, increasing the pH to about 4.5 - 8.5 and causing the formation of a floc. The alkaline composition is then added to bring the pH to about 9 to 10, causing the further formation of a floc. Optionally, air oxidation is carried out, reducing the pH to about 8.1 - 8.6. Optionally, a ferric or ferrous salt may also be added. The flocs comprise metal-lignin colloids, metal hydroxides and metal salts. The flocs coagulate to form a sludge. Optionally, fly ash or diatomaceous earth may be added to increase the density and stability of the sludge. The sludge that is formed contains the metals and is separated from the treated water by filtration. ";

Col0[105] = "This application relates to recombinant human interferon-like proteins. In one embodiment a recombinant protein created by gene shuffling technology is described having enhanced anti-viral and anti-proliferative activities in comparison to naturally occurring human interferon alpha 2b (HuIFN-.alpha.2b). The invention encompasses a polynucleotide encoding the protein and recombinant vectors and host cells comprising the polynucleotide. \rPreferably the polynucleotide is selected from the group of polynucleotides each having a sequence at least 93% identical to SEQ ID: No. 1 and the protein is selected from the group of proteins each having an amino acid sequence at least 85% identical to SEQ ID No: 2. The proteins and compositions comprising the proteins can be used for treatment of conditions responsive to interferon therapy, such as viral diseases and cancer. ";

Col0[106] = "A homogeneous fertilizer granule comprises slow-release (e.g. struvite) and fast release sources of phosphorus (P). The homogeneous fertilizer granule may further contain other essential nutrients and micronutrients required by plants. A number of methods may be used to make such granules. One method includes introducing a struvite slurry or fines and a liquid supply of water soluble P into a granulator. Alternatively, dry raw materials can be mixed with water/steam and/or another binder prior to being fed into a granulator. In another embodiment, pre-mixed dry raw materials are mechanically compacted and crushed to yield homogeneous fertilizer particles.";

Col0[107] = "Provided is a polyurethane foam which, when fitted to a human subject, exhibits excellent shape-following properties while exhibiting excellent comfortableness even during movement and when at rest. The polyurethane foam has toluene diisocyanate and polyether polyol as main components. The glass transition temperature, which is set to the temperature corresponding to the loss tangent peak value, is in the range 0°C-40°C inclusive. Under temperatures in the range 0°C-40°C inclusive, the loss tangent in the frequency domain 0.1Hz-100Hz inclusive is at least 0.4. The average value of the loss tangent in the frequency range 0.1Hz-1Hz inclusive is equal to or less than the average value of the loss tangent in the frequency range 10Hz-100Hz inclusive.";

Col0[108] = "Power spring configurations for a spring energized fastening device includes a compact double torsion power spring and two opposed compact single torsion springs. Simplified structures to hold the springs in a stable pre-loaded position are disclosed. Each coil has forward extending arms including an angled portion and forward vertically coincident portions. The double torsion spring has a self-locking crossing geometry to hold a pre-loaded rest position. The opposed two springs have a bridge and a mandrel to hold the rest position. A lever presses arms of the spring between a striker and the coil including a compact nesting condition. A tab of the striker extends forward to provide a release edge and a positioning torque bias upon the striker.";

Col0[109] = "A medicated formulation and method of use for treating migraine having a combination of active ingredients including: nicotine, and tryptophan alone and also with phenylalanine and/or, tyrosine, and/or caffeine in an aqueous solution.";

Col0[110] = "A method of inhibiting biofilm growth on a surface in an aqueous system comprising contacting a surface susceptible to biofilm growth with a solution comprising an amount of a non-decomposed moss or non-decomposed moss extract effective to inhibit biofilm growth. A method of removing biofilm from a surface in an aqueous system comprising contacting a surface having a biofilm with a solution containing an amount of a non-decomposed moss or non-decomposed moss extract effective to remove some or all of the biofilm from the surface.";

Col0[111] = "A method for intercepting calls from a remote or mobile device (100) for customer self-support detects when users or subscribers dial one or more predetermined numbers. If the number corresponds to one of the predetermined numbers (such as a customer support number), the phone may intercept the call and display a list of potential solutions to the subscriber\'s problems. \rVarious other features and embodiments art disclosed. ";

Col0[112] = "Shoes and shoe sole assemblies and associated methods of manufacture are disclosed herein. One aspect of the invention is directed toward a shoe and shoe sole assembly made of a non-linearly viscous, SEBS block copolymer-based material that becomes more resilient as more energy is applied. The shoe and shoe sole assembly is configured with a heel and forefoot insert configured to fit within a recess in a midsole. In other embodiments, the non-linearly viscous, SEBS block copolymer-based material is mixed with at least one other polymer in a foam. The midsole is formed with a heel impact region and a forefoot region made of the foam.";

Col0[113] = "An electrolytic cell comprising a pair of electrodes connected to a source of electrical current an electrolyte in fluid communication with the electrodes; a first gas, formed at the first electrode; \ra second gas formed at the second electrode; a separa-tor, and first and second gas collection vessels. The separator includes a first inclined surface to direct flow of the electrolyte and the first gas in a direction distal the second electrode and towards the first gas collection vessel due to a difference between densi-ty of the electrolyte and combined density of the electrolyte and the first gas. \rThe separator includes an second inclined surface to direct flow of the electrolyte and the second gas in a direction distal the first electrode and towards the second gas collection ves-sel due to a difference between density of the electrolyte and combined density of the electrolyte and the second gas. ";

Col0[114] = "In one embodiment of the present invention an electrolytic cell is provided comprising a containment vessel; a first electrode; a second electrode;\ra source of electrical current in electrical communication with the first electrode and the second electrode; an electrolyte in fluid communication with the first electrode and the second electrode; a gas, wherein the gas is formed during electrolysis at or near the first electrode; and a separator; wherein the separator includes an inclined surface to direct flow of the electrolyte and the gas due to a difference between density of the electrolyte and the combined density of the electrolyte and the gas such that the gas substantially flows in a direction distal to the second electrode. ";

Col0[115] = "In one embodiment of the present invention an electrolytic cell is provided comprising: a containment vessel; a first electrode; a second electrode; a source of electrical current in electrical communication with the first electrode and the second electrode; an electrolyte in fluid communication with the first electrode and the second electrode; a gas, wherein the gas is formed during electrolysis at or near the first electrode; and a separator; wherein the first electrode is configured to control the location of nucleation of the gas by substantially separating the location of electron transfer and nucleation. ";

Col0[116] = "The present disclosure is directed to a system and method of providing energy to a dwelling. An engine is housed within an inner tank, which is in turn housed within an outer tank. The engine provides electricity which is used for a dwelling. Exhaust fumes from the engine are piped through a series of heat- exchanging tubes within the outer tank to heat potable water within the outer tank. Water enters the potable tank at a bottom of the tank, and warms as it rises through the outer tank toward an outlet near a top of the outer tank. Hot, potable water is provided from the top of the outer tank to the dwelling. Condensate from the exhaust is captured and used as potable water. Heat, vibration, and acoustic energy from the engine is captured by the fluid in the inner tank and transferred to the outer tank.";

Col0[117] = "One embodiment of the present disclosure is directed to an insulator comprising a ceramic composition, wherein the ceramic composition comprises about 25-60% SiO2; 15-35% R2O3, wherein the R2O3 is 3-15% B2O3 and 5-25% AI2O3; 4- 25% MgO+0-7% Li2O, wherein the total of MgO+Li2O is between about 6-25%; 2-20% R2O, wherein the R2O is 0-15% Na2O, 0-15% K2O, 0-15% Rb2O; 0-15% Rb2O; 0-20% Cs2O; and 4-20% F; crystalline grains, wherein the crystalline grains are substantially oriented to extend in a first direction to provide improved insulating properties in a direction perpendicular to the first direction, wherein the first direction is circumferential and the direction perpendicular to the first direction is radial; and a first zone and a second zone, wherein the first zone is in compression and the second zone is in tension.";

Col0[118] = "The present disclosure is directed to fuel injectors that provide efficient injection, ignition, and combustion of various types of fuels. One example of such an injector can include a sensor that detects one or more conditions in the combustion chamber. The injector can also include an acoustical force generator or modifier that is responsive to the sensor and can be configured to (a) induce vibrations in the fuel in the injector body and/or in the combustion chamber, (b) induce vibrations in air in the combustion chamber, (c) induce vibrations in a valve driver or other injector component to actuate a flow valve, and/or (d) control patterning of fuel injected into the combustion chamber.";

export default Col0